### ISSUE TITLE
Delegate 调用报错 System.Delegate.Combine JsEnv.UsingAction 使用疑问

### ISSUE THREAD

**Issue by wulei** [Tencent/puerts#100]
C# 定义如下：

```
    public delegate void OnWebSocketOpenDelegate(WebSocket webSocket);
    public delegate void OnWebSocketMessageDelegate(WebSocket webSocket, string message);
    public delegate void OnWebSocketBinaryDelegate(WebSocket webSocket, byte[] data);
    public delegate void OnWebSocketClosedDelegate(WebSocket webSocket, UInt16 code, string message);
    public delegate void OnWebSocketErrorDelegate(WebSocket webSocket, string reason);

```

调用代码如下：
```
        ws.OnClosed = System.Delegate.Combine(ws.OnClosed, new BestHTTP.WebSocket.OnWebSocketClosedDelegate((w, c, msg) => {
            console.log("close:" + w)
            console.log("close:" + c)
            console.log("close:" + msg)
        })) as BestHTTP.WebSocket.OnWebSocketClosedDelegate;
```

报错如下：

```
Exception: /learn/Assets/StreamingAssets/scripts/bundle.js:645: Error: c# exception:can not find delegate bridge for BestHTTP.WebSocket.OnWebSocketClosedDelegate,stack:  at Puerts.GeneralGetterManager+<>c__DisplayClass25_0.<MakeTranslateFunc>b__1 (System.IntPtr isolate, Puerts.IGetValueFromJs getValueApi, System.IntPtr value, System.Boolean isByRef) [0x00047] in /learn/Assets/Lib/Puerts/Puerts/Src/DataTranslate.cs:226 
  at Puerts.DelegateConstructWrap.Construct (System.IntPtr isolate, System.IntPtr info, System.Int32 argumentsLen) [0x00039] in /learn/Assets/Lib/Puerts/Puerts/Src/MethodReflection.cs:305 
        csharp_1.System.Delegate.Combine(ws.OnClosed, new csharp_1.BestHTTP.WebSocket.OnWebSocketClosedDelegate((w, c, msg) => {
                                                      ^
Error: c# exception:can not find delegate bridge for BestHTTP.WebSocket.OnWebSocketClosedDelegate,stack:  at Puerts.GeneralGetterManager+<>c__DisplayClass25_0.<MakeTranslateFunc>b__1 (System.IntPtr isolate, Puerts.IGetValueFromJs getValueApi, System.IntPtr value, System.Boolean isByRef) [0x00047] in /learn/Assets/Lib/Puerts/Puerts/Src/DataTranslate.cs:226 
  at Puerts.DelegateConstructWrap.Construct (System.IntPtr isolate, System.IntPtr info, System.Int32 argumentsLen) [0x00039] in /learn/Assets/Lib/Puerts/Puerts/Src/MethodReflection.cs:305 
    at GameMain.HelloWs (/learn/Assets/StreamingAssets/scripts/bundle.js:645:55)
    at new GameMain (/learn/Assets/StreamingAssets/scripts/bundle.js:627:14)
    at Object.<anonymous> (/learn/Assets/StreamingAssets/scripts/bundle.js:665:22)
    at Object../src/GameMain.ts (/learn/Assets/StreamingAssets/scripts/bundle.js:667:30)
    at __webpack_require__ (/learn/Assets/StreamingAssets/scripts/bundle.js:20:30)
    at /learn/Assets/StreamingAssets/scripts/bundle.js:84:18
    at /learn/Assets/StreamingAssets/scripts/bundle.js:87:10
    at /learn/Assets/StreamingAssets/scripts/bundle.js:1443:3
    at /learn/Assets/StreamingAssets/scripts/bundle.js:1443:76
    at executeModule (/learn/Assets/StreamingAssets/scripts/puerts/modular.js:46:23)
Puerts.JsEnv.Eval (System.String chunk, System.String chunkName) (at Assets/Lib/Puerts/Puerts/Src/JsEnv.cs:145)
JsManager.StartGame () (at Assets/Scripts/Puerts/JsManager.cs:42)
JsManager.Awake () (at Assets/Scripts/Puerts/JsManager.cs:25)
UnityEngine.GameObject:AddComponent()
MonoSingleton`1:get_Instance() (at Assets/Scripts/Common/MonoSingleton.cs:16)
JsBehaviour:Awake() (at Assets/Scripts/Puerts/JsBehaviour.cs:15)


```

**Comment by wulei** [comment]
找到faq了，谢谢

**Comment by wulei** [comment]
```
该delegate带了值类型参数或者返回值，解决办法：如果没有返回值，用JsEnv.UsingAction声明下，有返回值就用JsEnv.UsingFunc声明。
```

看了一下faq还是没太明白这里的使用，指点一下

**Comment by chexiongsheng** [comment]
UsingFunc能支持返回值，UsingAction不能，就和System下的Func和Action一样
