### ISSUE TITLE
[Unity] I found a bug, 生成代码后第一次可以正常运行, Stop 之后再 Play, 同样的流程会随机出错.

### ISSUE THREAD

**Issue by liu3656** [Tencent/puerts#1012]
主要流程为, 在 TS 内, 尝试通过把一个 c# object cast 成 c# Interface 并访问 Interface 内的 Property (错误信息内的 VarStore 即为 Interface 内的 Property). 

未修改过代码, 运行会随机的 可以执行 或 报错, 具体错误信息请参见 error log 部分.

Puerts binding 设置内, 启用了 Js 访问控制的 filter, 对未在列表内的类型使用了 BindingMode.DontBinding. 猜测可能是这部分的问题, 但在删除 filter 配置并重新生成代码后该错误仍会出现.

以上部分的测试都在未开启 domain reload 的情况下进行.
猜测或许会和 domain reload 有关. 但在开启 domain reload 并重启 unity 之后, 该现象仍然存在.

目前已知的情况是, 若清除所有 code gen 代码并重新生成, 第一次运行一定不会报错. (大约试了有个20来次, 没有一次出错的)

如有需要更多信息我们可以提供, 也可以开直播复现问题. 谢谢!

## error log | 日志或报错信息
![image](https://user-images.githubusercontent.com/11775398/192917209-e8121906-7094-4f79-a496-e7a525c1897c.png)

Js container bind error: System.Exception: J:\Dev\PV-develop\Assets\Game\DesignerScripts\Output\hybrid\contents\rules\example.cjs:17: TypeError: Cannot read property 'GetIntVar' of undefined
TypeError: Cannot read property 'GetIntVar' of undefined
    at RuleExample.OnBind (J:\Dev\PV-develop\Assets\Game\DesignerScripts\Output\hybrid\contents\rules\example.cjs:17:57)
    at BindRule (J:\Dev\PV-develop\Assets\Game\DesignerScripts\Output\hybrid\modules.cjs:61:12)
    at BindDelegates.controller.bindDelegate (J:\Dev\PV-develop\Assets\Game\DesignerScripts\Output\hybrid\modules.cjs:37:62)
  at Puerts.GenericDelegate.Action[T1,T2,T3] (T1 p1, T2 p2, T3 p3) [0x0006b] in J:\Dev\PV-develop\Assets\ThirdParty\PuerTS\Runtime\Src\JSType\GenericDelegate.cs:482 
  at Game.Hybrid.Scripting.JsHybridManager.BindRule (Mistold.Unity.IEntity entity, System.String scriptId, System.Boolean isLoading) [0x00002] in J:\Dev\PV-develop\Assets\Game\Scripts\Hybrid.Scripting\JsHybridManager.cs:118 

![image](https://user-images.githubusercontent.com/11775398/192917333-1d08c000-fc92-456b-9d85-0c9c408be0a7.png)

## context | 编译/运行环境
Unity 2021.3.5f1 with PuerTS 1.3.8.
## how to reproduce | 复现步骤
1. N/A

**Comment by zombieyang** [comment]
提及的特征有点多，首先比如将C#对象cast成interface，如果用的是as，在ts里这个操作其实没有实际意义的，编译成JS后代码长得都一样。

其次filter过滤的应该是类型里的字段，过滤类型是没什么用的

---

该问题只有在你们的项目内复现吗 能否抠出一个比较小的可复现demo

**Comment by liu3656** [comment]
对于 filter, 我检查了 memberInfo.DeclaringType, 用于屏蔽不允许访问的类型 (即, 即使知道某些未生成代码的可访问信息, 因为类型不在列表内也不允许访问).

我可能可以专门做一个小 demo, 但我不确定这个问题是否还会出现.

**Comment by liu3656** [comment]
我尝试把抽出来写了个最简单的工程, 但是这个问题没有再出现. 
可能这个只能在我们大工程里被复现, 不然去 discord 我直播给你看看?

**Comment by zombieyang** [comment]
可以，不过我没怎么深入用过discord。你先给我发个私信？

**Comment by liu3656** [comment]
额, 我在美西时区. 等你今天来了我给你看. 
qq, discord, 腾讯会议什么的 , 我都可以. 选一个你方便的就行.

**Comment by zombieyang** [comment]
你在discord上给我留个言吧我不知道你是哪个

**Comment by zombieyang** [comment]
怀疑是该bug，一会发布1.3.9之后验证。
e985c29b91cf34016d9f0fa4a94c5e0b83696f20
