### ISSUE TITLE
[Unity] Bug: 示例项目1_Start_Template中，调用扩展方法报错"TypeError: a.GetAAAA is not a function"

### ISSUE THREAD

**Issue by ankisme** [Tencent/puerts#1060]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unity/zhcn/readme)/[Doc](https://puerts.github.io/unity/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [x] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unity/zhcn/faq.md)

### Puer的版本 | Puer Version

1.4.0rc

### Unity的版本 | Unity Version

2022.1.0b13

### 发生在哪个平台 | Platform

Editor(win)

### 错误信息 | Error Message

```ts
Exception: E:\proj\other\puerts_unity_demo\projects\1_Start_Template\Assets\Samples\TSBehaviour\Resources\rotate.mjs:16: TypeError: a.GetAAAA is not a function

TypeError: a.GetAAAA is not a function
    at Object.handler (E:\proj\other\puerts_unity_demo\projects\1_Start_Template\Assets\Samples\TSBehaviour\Resources\rotate.mjs:16:28)
    at timerUpdate (E:\proj\other\puerts_unity_demo\projects\1_Start_Template\Assets\Samples\TSBehaviour\Resources\puerts\timer.mjs:110:22)
Puerts.JsEnv.Tick () (at E:/proj/other/puerts_unity_demo/package/Runtime/Src/JsEnv.cs:692)
PuertsTest.TSBehaviour.Update () (at Assets/Samples/TSBehaviour/TSBehaviour.cs:59)
```

### 问题重现 | Bug reproduce

参见下方的文件，主要的改动就是新增了一个class A，然后调用GetAAAA方法会导致报错`TypeError: a.GetAAAA is not a function`

这是修改过的1_start_template\Assets\Samples\TSBehaviour\TSBehaviour.cs
```c#
using UnityEngine;
using Puerts;
using System;
using System.Collections;

public class A
{
	public int a = 2;
	public int GetBBBB()
	{
		return this.a * 100;
	}
}

public static class ExtendedMethod
{
	public static int GetAAAA(this A a)
	{
		return a.a * 100;
	}
}

namespace PuertsTest
{
    public delegate void ModuleInit(TSBehaviour monoBehaviour);

    //只是演示纯用js实现MonoBehaviour逻辑的可能，
    //但从性能角度这并不是最佳实践，会导致过多的跨语言调用
    public class TSBehaviour : MonoBehaviour
    {
        public string ModuleName;//可配置加载的js模块

        public Action JsStart;
        public Action JsUpdate;
        public Action JsOnDestroy;

        static JsEnv jsEnv;

        private void OnEnable()
        {
            string root = Application.dataPath + "/Samples/TSBehaviour/Resources";
            if (jsEnv == null) jsEnv = new JsEnv(new DefaultLoader(root), 9229);
            var varname = "m_" + Time.frameCount;
            var init = jsEnv.ExecuteModule<ModuleInit>(ModuleName, "init");

            if (init != null) init(this);

            Application.runInBackground = true;
        }

        private void OnDisable()
        {
            if (JsOnDestroy != null) JsOnDestroy();
        }

        void Start()
        {
            if (JsStart != null) JsStart();
        }

        void Update()
        {
            jsEnv.Tick();
            if (JsUpdate != null) JsUpdate();
        }

        void OnDestroy()
        {
            JsStart = null;
            JsUpdate = null;
            JsOnDestroy = null;
        }

        public IEnumerator Coroutine()
        {
            yield return new WaitForSeconds(1);
            UnityEngine.Debug.Log("coroutine done");
        }
    }
}
```

这是修改过的1_Start_Template\Assets\Samples\Editor\01_WrapperGenerate\ExamplesCfg.cs
```c#
/*
 * Tencent is pleased to support the open source community by making InjectFix available.
 * Copyright (C) 2019 THL A29 Limited, a Tencent company.  All rights reserved.
 * InjectFix is licensed under the MIT License, except for the third-party components listed in the file 'LICENSE' which may be subject to their corresponding license terms.
 * This file is subject to the terms and conditions defined in file 'LICENSE', which is part of this source code package.
 */

using System.Collections.Generic;
using Puerts;
using System;
using UnityEngine;

//1、配置类必须打[Configure]标签
//2、必须放Editor目录
[Configure]
public class ExamplesCfg
{
    [Binding]
    static IEnumerable<Type> Bindings
    {
        get
        {
            return new List<Type>()
            {
                typeof(Debug),
                typeof(Vector3),
                typeof(List<int>),
                typeof(Dictionary<string, List<int>>),
                typeof(Time),
                typeof(Transform),
                typeof(Component),
                typeof(GameObject),
                typeof(UnityEngine.Object),
                typeof(Delegate),
                typeof(System.Object),
                typeof(System.Array),
                typeof(Type),
                typeof(ParticleSystem),
                typeof(Canvas),
                typeof(RenderMode),
                typeof(Behaviour),
                typeof(MonoBehaviour),

                typeof(PuertsTest.TSBehaviour),
                typeof(TSProperties),
				typeof(A),
				typeof(ExtendedMethod),

                typeof(UnityEngine.EventSystems.UIBehaviour),
                typeof(UnityEngine.UI.Selectable),
                typeof(UnityEngine.UI.Button),
                typeof(UnityEngine.UI.Button.ButtonClickedEvent),
                typeof(UnityEngine.Events.UnityEvent),
                typeof(UnityEngine.UI.InputField),
                typeof(UnityEngine.UI.Toggle),
                typeof(UnityEngine.UI.Toggle.ToggleEvent),
                typeof(UnityEngine.Events.UnityEvent<bool>),
            };
        }
    }

    [BlittableCopy]
    static IEnumerable<Type> Blittables
    {
        get
        {
            return new List<Type>()
            {
                //打开这个可以优化Vector3的GC，但需要开启unsafe编译
                //typeof(Vector3),
            };
        }
    }

    [Filter]
    static bool FilterMethods(System.Reflection.MemberInfo mb)
    {
        // 排除 MonoBehaviour.runInEditMode, 在 Editor 环境下可用发布后不存在
        if (mb.DeclaringType == typeof(MonoBehaviour) && mb.Name == "runInEditMode") {
            return true;
        }
        return false;
    }
}
```

这是修改过的1_Start_Template\Puer-Project\src\rotate.ts
```ts
class Rotate {
	public speed: number = 0;

	private bindTo: CS.PuertsTest.TSBehaviour

	constructor(bindTo: CS.PuertsTest.TSBehaviour) {
		this.bindTo = bindTo
		this.bindTo.JsUpdate = () => this.onUpdate()
		this.bindTo.JsOnDestroy = () => this.onDestroy()

		const propsComponent: CS.TSProperties = this.bindTo.GetComponent(puerts.$typeof(CS.TSProperties)) as CS.TSProperties
		for (let i = 0; i < propsComponent.Pairs.Length; i++) {
			const p = propsComponent.Pairs.get_Item(i)
			//@ts-ignore
			this[p.key] = p.value
		}
		setInterval(() => {
			const a = new CS.A

			console.log('a.GetBBBB() = ' + a.GetBBBB())

			// 开启hot-reload时，你可以尝试修改该函数感受效果
			this.speed = a.GetAAAA()
			console.log('current speed is ' + this.speed)
		}, 1000)
	}

	onUpdate() {
		//js不支持操作符重载所以Vector3的乘这么用
		let r = CS.UnityEngine.Vector3.op_Multiply(CS.UnityEngine.Vector3.up, CS.UnityEngine.Time.deltaTime * this.speed)
		this.bindTo.transform.Rotate(r)
	}

	onDestroy() {
		console.log('onDestroy...')
	}
}

export function init(bindTo: CS.PuertsTest.TSBehaviour) {
	new Rotate(bindTo)
}
```

**Comment by zombieyang** [comment]
我2022.1.22没有复现出来，你有生成代码了吗？

**Comment by ankisme** [comment]
好吧，我没有生成代码，生成代码之后就正常了

我重新看了下官方文档[使用extension函数]，大概理解了，是新的puerts版本需要生成代码是吧，我之前用的puerts版本是今年2月的Unity_Plugin_1.2.3,Version:15，印象中以前在开发期间时可以不用生成代码

**Comment by zombieyang** [comment]
以前是会的，后来发现不太稳定关掉了，可以参考 PUERTS_REFLECT_ALL_EXTENSION 宏
