### ISSUE TITLE
[UE] Bug: TS 定义的ActorComponent，运行时创建失败，取得为空

### ISSUE THREAD

**Issue by zidanebest** [Tencent/puerts#1194]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

Unreal_v1.0.2

### UE的版本 | UE Version

4.27

### 发生在哪个平台 | Platform

Editor(Win)

### 错误信息 | Error Message

Puerts: Error: (0x0000016D95071710) call TS_Bullet_C::ReceiveActorBeginOverlap of 0000016E20894B80 fail: C:\MainDic\Cradle\Content\JavaScript\TS_Bullet.js:32: TypeError: TheHitCombatComp.OnHited is not a function
TypeError: TheHitCombatComp.OnHited is not a function
    at /Game/Blueprints/TypeScript/TS_Bullet.TS_Bullet_C.ReceiveActorBeginOverlap (C:\MainDic\Cradle\Content\JavaScript\TS_Bullet.js:32:30)
Puerts: Error: (0x0000016D95071710) call TS_Bullet_C::ReceiveActorBeginOverlap of 0000016E20894480 fail: C:\MainDic\Cradle\Content\JavaScript\TS_Bullet.js:32: TypeError: TheHitCombatComp.OnHited is not a function
TypeError: TheHitCombatComp.OnHited is not a function
    at /Game/Blueprints/TypeScript/TS_Bullet.TS_Bullet_C.ReceiveActorBeginOverlap (C:\MainDic\Cradle\Content\JavaScript\TS_Bullet.js:32:30)
    

### 问题重现 | Bug reproduce

尝试获取OtherActor身上的CombatCompBase组件，但是产生报错，调试打印显示拿到的是一个SkeletalMeshComp
![image](https://user-images.githubusercontent.com/45536222/216753682-124af556-bd7f-445c-b2e9-49cb630c24ec.png)
![image](https://user-images.githubusercontent.com/45536222/216753673-af681978-33de-4592-b8d3-489a6d74a885.png)
看上去是因为CombatComp是空的导致GetComponentByClass拿到了错误的组件。
CombatComp创建过程如下
![image](https://user-images.githubusercontent.com/45536222/216753788-9b184fe6-33f4-4e18-8be0-d7dbd3eec2eb.png)
![image](https://user-images.githubusercontent.com/45536222/216753801-2219b7b7-683c-4cbb-a95d-098b9fefc394.png)
CombatComp创建如下
![image](https://user-images.githubusercontent.com/45536222/216753826-a0d81c0a-6f2f-41d8-b27d-afe4b16dab37.png)
在之前代码中我使用CreateDefaultSubobjectGeneric函数创建引擎中的Comp并不会带来问题，而TS 中定义的Comp则会生成失败，打印为空。
当我创建的Comp继承自ActorComp时，创建为空，而继承自SceneComp时，拿到的是SceneComp而不是这个组件本身。
![image](https://user-images.githubusercontent.com/45536222/216754266-a8ca73c8-520e-4e51-8e07-54494e15c811.png)
![image](https://user-images.githubusercontent.com/45536222/216754311-c7b38edf-0382-46e2-96fd-819075de50b7.png)

**Comment by zidanebest** [comment]
![image](https://user-images.githubusercontent.com/45536222/216757699-bafa18ce-e609-48ac-be97-927dbf0ae6b9.png)
CreateDefaultSubobject函数创建TS类的时候，需要写入蓝图类而不是TS类
