### ISSUE TITLE
[UE] Bug: android上crash，提示  dlopen failed: library "libnode.so" not found

### ISSUE THREAD

**Issue by luochanganz** [Tencent/puerts#1331]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

Unreal v1.0.3

### UE的版本 | UE Version

UE 5.1.1

### 发生在哪个平台 | Platform

Android

### 错误信息 | Error Message

java.lang.UnsatisfiedLinkError: dlopen failed: library "[libnode.so](http://libnode.so/)" not found: needed by /data/app/~~t-YaGyzeIH4iUHTGzR3e-g==/com.xxx.xxx-mt_ss86-qrUmfDwOq6rRlQ==/lib/arm64/[libUnreal.so](http://libunreal.so/) in namespace classloader-namespace
	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
	at java.lang.System.loadLibrary(System.java:1661)
	at com.epicgames.unreal.GameActivity.<clinit>(GameActivity.java:6837)
	at java.lang.Class.newInstance(Native Method)
	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
	at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45)
	at android.app.Instrumentation.newActivity(Instrumentation.java:1340)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3715)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3971)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2389)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8261)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

### 问题重现 | Bug reproduce

nodejs_16后端 打包至Android平台即可
nodejs使用的是https://github.com/puerts/backend-nodejs/releases/tag/NodeJS_16.16.0_230209

**Comment by chexiongsheng** [comment]
puerts用的是静态链接：https://github.com/Tencent/puerts/blob/master/unreal/Puerts/Source/JsEnv/JsEnv.Build.cs#L433
不会用libnode.so，是你做的修改吧？

**Comment by luochanganz** [comment]
> puerts用的是静态链接：https://github.com/Tencent/puerts/blob/master/unreal/Puerts/Source/JsEnv/JsEnv.Build.cs#L433 不会用libnode.so，是你做的修改吧？

没有做修改，用的就是github的版本，将JsEnv.Build.cs中的
` #if UE_4_19_OR_LATER
                        AdditionalPropertiesForReceipt.Add("AndroidPlugin", Path.Combine(ModuleDirectory, "..", "..", "ThirdParty", "Libnode_APL.xml"));
            #else
                        AdditionalPropertiesForReceipt.Add(new ReceiptProperty("AndroidPlugin", Path.Combine(ModuleDirectory, "..", "..", "ThirdParty", "Libnode_APL.xml")));
            #endif`

取消注释后就可以了...比较奇怪

**Comment by chexiongsheng** [comment]
那不就修改么？那是另外一种方式，你这相当于同时静态链接又动态链接了吧？
不用修改，直接用就可以了，注释掉的是之前探索的另外一种方式。

**Comment by luochanganz** [comment]
> 那不就修改么？那是另外一种方式，你这相当于同时静态链接又动态链接了吧？ 不用修改，直接用就可以了，注释掉的是之前探索的另外一种方式。

我试过原版本(上面的话注释掉)去打包，但是会报一开始的错；
取消注释后打包，就不会报错了；
空下来后我查查原版打包是不是我哪里姿势不对导致的报错；

**Comment by chexiongsheng** [comment]
原版就不需要libnode.so

**Comment by chexiongsheng** [comment]
据一个项目反馈加上libopenssl.a就可以了
