### ISSUE TITLE
[Unity] Bug: xIl2cpp模式下调用websocket发送接口时闪退

### ISSUE THREAD

**Issue by huntwx** [Tencent/puerts#1466]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unity/zhcn/readme)/[Doc](https://puerts.github.io/unity/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unity/zhcn/faq.md)

### Puer的版本 | Puer Version

Unity_v2.0.0

### Unity的版本 | Unity Version

2019.4.39f1

### 发生在哪个平台 | Platform

Android

### 错误信息 | Error Message

闪退的dump信息：
2023-08-16 17:18:52.103 1256-1256/? E/PocketModeEvent: PocketModeSetting is off 
2023-08-16 17:18:52.111 2399-9510/? E/SecPowerUI.Notification: no saved value, so we do nothing !!
2023-08-16 17:18:55.948 11449-11471/? E/CRASH: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
2023-08-16 17:18:55.948 11449-11471/? E/CRASH: Version '2019.4.39f1 (78d14dfa024b)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'arm64-v8a'
2023-08-16 17:18:55.948 11449-11471/? E/CRASH: Build fingerprint: 'samsung/y2qzcx/y2q:13/TP1A.220624.014/G9860ZCU4HWD2:user/release-keys'
2023-08-16 17:18:55.948 11449-11471/? E/CRASH: Revision: '14'
2023-08-16 17:18:55.948 11449-11471/? E/CRASH: ABI: 'arm64'
2023-08-16 17:18:55.948 11449-11471/? E/CRASH: Timestamp: 2023-08-16 17:18:55+0800
2023-08-16 17:18:55.948 11449-11471/? E/CRASH: pid: 11449, tid: 11471, name: UnityMain  >>> com.DefaultCompany.Unity <<<
2023-08-16 17:18:55.948 11449-11471/? E/CRASH: uid: 10478
2023-08-16 17:18:55.948 11449-11471/? E/CRASH: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x12e
2023-08-16 17:18:55.948 11449-11471/? E/CRASH: Cause: null pointer dereference
2023-08-16 17:18:55.948 11449-11471/? E/CRASH:     x0  0000000000000000  x1  0000000000000000  x2  00000074a0b1c018  x3  0000000000000000
2023-08-16 17:18:55.948 11449-11471/? E/CRASH:     x4  b40000754b4fb050  x5  0000007380b41599  x6  00000074a0b1c258  x7  0000000000000002
2023-08-16 17:18:55.948 11449-11471/? E/CRASH:     x8  00000000000000a5  x9  000000000000000a  x10 0000000000000002  x11 00000073db3e6670
2023-08-16 17:18:55.948 11449-11471/? E/CRASH:     x12 0000000000000026  x13 0000000000000062  x14 0000000000000007  x15 0000007380b436e8
2023-08-16 17:18:55.948 11449-11471/? E/CRASH:     x16 00000073ddae8698  x17 00000073db1d9e7c  x18 0000000016f19d5a  x19 0000000000000000
2023-08-16 17:18:55.948 11449-11471/? E/CRASH:     x20 b4000075eb509910  x21 0000000000000001  x22 00000073ddca6000  x23 00000073ddca6000
2023-08-16 17:18:55.948 11449-11471/? E/CRASH:     x24 b4000075eb509910  x25 00000073ddca9000  x26 0000000000000000  x27 0000000000000002
2023-08-16 17:18:55.948 11449-11471/? E/CRASH:     x28 00000073ddca9000  x29 00000074a0b1bec0
2023-08-16 17:18:55.948 11449-11471/? E/CRASH:     sp  00000074a0b1beb0  lr  00000073da4f5aa8  pc  00000073da4f25d0
2023-08-16 17:18:55.948 11449-11471/? E/CRASH: backtrace:
2023-08-16 17:18:55.948 11449-11471/? E/CRASH:       #00 pc 0000000000bd75d0  /data/app/~~jUSPbd2Nd3k-G90AG4yMyg==/com.DefaultCompany.Unity-C_Qs1xKa6vpEVR1moxaqDg==/lib/arm64/libil2cpp.so (BuildId: 74e963f0f23fe387a3aacf560f924d35eb2f5dfc)
2023-08-16 17:18:55.948 11449-11471/? E/CRASH:       #01 pc 0000000000bdaaa4  /data/app/~~jUSPbd2Nd3k-G90AG4yMyg==/com.DefaultCompany.Unity-C_Qs1xKa6vpEVR1moxaqDg==/lib/arm64/libil2cpp.so (BuildId: 74e963f0f23fe387a3aacf560f924d35eb2f5dfc)
2023-08-16 17:18:55.949 11449-11471/? E/CRASH:       #02 pc 00000000016fecc4  /data/app/~~jUSPbd2Nd3k-G90AG4yMyg==/com.DefaultCompany.Unity-C_Qs1xKa6vpEVR1moxaqDg==/lib/arm64/libil2cpp.so (BuildId: 74e963f0f23fe387a3aacf560f924d35eb2f5dfc)
2023-08-16 17:18:55.949 11449-11471/? E/CRASH:       #03 pc 0000000000bae65c  /data/app/~~jUSPbd2Nd3k-G90AG4yMyg==/com.DefaultCompany.Unity-C_Qs1xKa6vpEVR1moxaqDg==/lib/arm64/libil2cpp.so (BuildId: 74e963f0f23fe387a3aacf560f924d35eb2f5dfc)
2023-08-16 17:18:55.949 11449-11471/? E/CRASH:       #04 pc 0000000001e72130  /data/app/~~jUSPbd2Nd3k-G90AG4yMyg==/com.DefaultCompany.Unity-C_Qs1xKa6vpEVR1moxaqDg==/lib/arm64/libil2cpp.so (BuildId: 74e963f0f23fe387a3aacf560f924d35eb2f5dfc)
2023-08-16 17:18:55.949 11449-11471/? E/CRASH:       #05 pc 0000000001e71820  /data/app/~~jUSPbd2Nd3k-G90AG4yMyg==/com.DefaultCompany.Unity-C_Qs1xKa6vpEVR1moxaqDg==/lib/arm64/libil2cpp.so (BuildId: 74e963f0f23fe387a3aacf560f924d35eb2f5dfc)
2023-08-16 17:18:55.949 11449-11471/? E/CRASH:       #06 pc 0000000001e70fd8  /data/app/~~jUSPbd2Nd3k-G90AG4yMyg==/com.DefaultCompany.Unity-C_Qs1xKa6vpEVR1moxaqDg==/lib/arm64/libil2cpp.so (BuildId: 74e963f0f23fe387a3aacf560f924d35eb2f5dfc)
2023-08-16 17:18:55.949 11449-11471/? E/CRASH:       #07 pc 0000000001d7ad88  /data/app/~~jUSPbd2Nd3k-G90AG4yMyg==/com.DefaultCompany.Unity-C_Qs1xKa6vpEVR1moxaqDg==/lib/arm64/libil2cpp.so (BuildId: 74e963f0f23fe387a3aacf560f924d35eb2f5dfc)
2023-08-16 17:18:56.049 11449-11471/? E/CRASH: Tombstone written to: /storage/emulated/0/Android/data/com.DefaultCompany.Unity/files/tombstone_01
    
    --------- beginning of crash
2023-08-16 17:18:56.050 11449-11471/? E/AndroidRuntime: FATAL EXCEPTION: UnityMain
    Process: com.DefaultCompany.Unity, PID: 11449
    java.lang.Error: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
    Version '2019.4.39f1 (78d14dfa024b)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'arm64-v8a'
    Build fingerprint: 'samsung/y2qzcx/y2q:13/TP1A.220624.014/G9860ZCU4HWD2:user/release-keys'
    Revision: '14'
    ABI: 'arm64'
    Timestamp: 2023-08-16 17:18:55+0800
    pid: 11449, tid: 11471, name: UnityMain  >>> com.DefaultCompany.Unity <<<
    uid: 10478
    signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x12e
    Cause: null pointer dereference
        x0  0000000000000000  x1  0000000000000000  x2  00000074a0b1c018  x3  0000000000000000
        x4  b40000754b4fb050  x5  0000007380b41599  x6  00000074a0b1c258  x7  0000000000000002
        x8  00000000000000a5  x9  000000000000000a  x10 0000000000000002  x11 00000073db3e6670
        x12 0000000000000026  x13 0000000000000062  x14 0000000000000007  x15 0000007380b436e8
        x16 00000073ddae8698  x17 00000073db1d9e7c  x18 0000000016f19d5a  x19 0000000000000000
        x20 b4000075eb509910  x21 0000000000000001  x22 00000073ddca6000  x23 00000073ddca6000
        x24 b4000075eb509910  x25 00000073ddca9000  x26 0000000000000000  x27 0000000000000002
        x28 00000073ddca9000  x29 00000074a0b1bec0
        sp  00000074a0b1beb0  lr  00000073da4f5aa8  pc  00000073da4f25d0
    
    backtrace:
          #00 pc 0000000000bd75d0  /data/app/~~jUSPbd2Nd3k-G90AG4yMyg==/com.DefaultCompany.Unity-C_Qs1xKa6vpEVR1moxaqDg==/lib/arm64/libil2cpp.so (BuildId: 74e963f0f23fe387a3aacf560f924d35eb2f5dfc)
          #01 pc 0000000000bdaaa4  /data/app/~~jUSPbd2Nd3k-G90AG4yMyg==/com.DefaultCompany.Unity-C_Qs1xKa6vpEVR1moxaqDg==/lib/arm64/libil2cpp.so (BuildId: 74e963f0f23fe387a3aacf560f924d35eb2f5dfc)
          #02 pc 00000000016fecc4  /data/app/~~jUSPbd2Nd3k-G90AG4yMyg==/com.DefaultCompany.Unity-C_Qs1xKa6vpEVR1moxaqDg==/lib/arm64/libil2cpp.so (BuildId: 74e963f0f23fe387a3aacf560f924d35eb2f5dfc)
          #03 pc 0000000000bae65c  /data/app/~~jUSPbd2Nd3k-G90AG4yMyg==/com.DefaultCompany.Unity-C_Qs1xKa6vpEVR1moxaqDg==/lib/arm64/libil2cpp.so (BuildId: 74e963f0f23fe387a3aacf560f924d35eb2f5dfc)
          #04 pc 0000000001e72130  /data/app/~~jUSPbd2Nd3k-G90AG4yMyg==/com.DefaultCompany.Unity-C_Qs1xKa6vpEVR1moxaqDg==/lib/arm64/libil2cpp.so (BuildId: 74e963f0f23fe387a3aacf560f924d35eb2f5dfc)
          #05 pc 0000000001e71820  /data/app/~~jUSPbd2Nd3k-G90AG4yMyg==/com.DefaultCompany.Unity-C_Qs1xKa6vpEVR1moxaqDg==/lib/arm64/libil2cpp.so (BuildId: 74e963f0f23fe387a3aacf560f924d35eb2f5dfc)
          #06 pc 0000000001e70fd8  /data/app/~~jUSPbd2Nd3k-G90AG4yMyg==/com.DefaultCompany.Unity-C_Qs1xKa6vpEVR1moxaqDg==/lib/arm64/libil2cpp.so (BuildId: 74e963f0f23fe387a3aacf560f924d35eb2f5dfc)
          #07 pc 0000000001d7ad88  /data/app/~~jUSPbd2Nd3k-G90AG4yMyg==/com.DefaultCompany.Unity-C_Qs1xKa6vpEVR1moxaqDg==/lib/arm64/libil2cpp.so (BuildId: 74e963f0f23fe387a3aacf560f924d35eb2f5dfc)
    
        at libil2cpp.0xbd75d0(Native Method)
        at libil2cpp.0xbdaaa4(Native Method)
        at libil2cpp.0x16fecc4(Native Method)
        at libil2cpp.0xbae65c(Native Method)
        at libil2cpp.0x1e72130(Native Method)
        at libil2cpp.0x1e71820(Native Method)
        at libil2cpp.0x1e70fd8(Native Method)
        at libil2cpp.0x1d7ad88(Native Method)
还原调用栈如下：
il2cpp::vm::Class::Init(Il2CppClass*)
C:\Unity\2019.4.39f1\Editor\Data\il2cpp\libil2cpp\vm/Class.cpp:1531
il2cpp::vm::Class::IsAssignableFrom(Il2CppClass*, Il2CppClass*)
C:\Unity\2019.4.39f1\Editor\Data\il2cpp\libil2cpp\vm/Class.cpp:610
puerts::IsAssignableFrom(void const*, void const*)
/home/wux/src/puerts-Unity_v2.0.0/unity/native_src_il2cpp/Src/Puerts.cpp:415
puerts::MethodCallback(pesapi_callback_info__*)
F:\jenkins\workspace\demontale-unity\dev\Unity\Temp\StagingArea\Il2Cpp\il2cppOutput/Puerts_il2cpp.cpp:235
v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo)
:?
v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments)
:?
v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*)
:?
Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit
:?

### 问题重现 | Bug reproduce

Ts 调用c# websocket发送数据接口时闪退，接口定义为Send ($buffer: ArrayBuffer, $onFinish?: System.Action) : void

**Comment by huntwx** [comment]
将此接口改为Send ($buffer: ArrayBuffer) : void就正常了，不会闪退。不过多了个Action的参数为什么会闪退呢？
