### ISSUE TITLE
Is it possible to use amplify-js from puerts ?

### ISSUE THREAD

**Issue by Kiddinglife** [Tencent/puerts#160]
FYI, amplify-js is a pure javascript library.
https://github.com/aws-amplify/amplify-js

I took some time but still could not get it work. I added require in QuickStart.js
```
"use strict";
require("aws-amplify");
Object.defineProperty(exports, "__esModule", { value: true });
const UE = require("ue");
const puerts_1 = require("puerts");
// import { Amplify } from "aws-amplify";
// const amplify = require("aws-amplify");
let obj = new UE.MainObject();
```
neither of them worked. I got the error:
```
Puerts: Error: (0x00000206226C5490) D:\EpicEngineProjects\puerts_unreal_demo\Content\JavaScript\node_modules\aws-amplify\dist\aws-amplify.js:201341: ReferenceError: self is not defined
module.exports = self.fetch || (self.fetch = __webpack_require__(/*! unfetch */ "../../node_modules/unfetch/dist/unfetch.module.js").default || __webpack_require__(/*! unfetch */ "../../node_modules/unfetch/dist/unfetch.module.js"));
                 ^
ReferenceError: self is not defined
    at Object.../../node_modules/isomorphic-unfetch/browser.js (D:\EpicEngineProjects\puerts_unreal_demo\Content\JavaScript\node_modules\aws-amplify\dist\aws-amplify.js:201341:18)
    at __webpack_require__ (D:\EpicEngineProjects\puerts_unreal_demo\Content\JavaScript\node_modules\aws-amplify\dist\aws-amplify.js:30:30)
    at Module.../amazon-cognito-identity-js/es/Client.js (D:\EpicEngineProjects\puerts_unreal_demo\Content\JavaScript\node_modules\aws-amplify\dist\aws-amplify.js:220229:76)
    at __webpack_require__ (D:\EpicEngineProjects\puerts_unreal_demo\Content\JavaScript\node_modules\aws-amplify\dist\aws-amplify.js:30:30)
    at Module.../amazon-cognito-identity-js/es/CognitoUserPool.js (D:\EpicEngineProjects\puerts_unreal_demo\Content\JavaScript\node_modules\aws-amplify\dist\aws-amplify.js:222917:65)
    at __webpack_require__ (D:\EpicEngineProjects\puerts_unreal_demo\Content\JavaScript\node_modules\aws-amplify\dist\aws-amplify.js:30:30)
    at Module.../amazon-cognito-identity-js/es/index.js (D:\EpicEngineProjects\puerts_unreal_demo\Content\JavaScript\node_modules\aws-amplify\dist\aws-amplify.js:223634:74)
    at __webpack_require__ (D:\EpicEngineProjects\puerts_unreal_demo\Content\JavaScript\node_modules\aws-amplify\dist\aws-amplify.js:30:30)
    at Module.../auth/lib-esm/Auth.js (D:\EpicEngineProjects\puerts_unreal_demo\Content\JavaScript\node_modules\aws-amplify\dist\aws-amplify.js:231906:84)
    at __webpack_require__ (D:\EpicEngineProjects\puerts_unreal_demo\Content\JavaScript\node_modules\aws-amplify\dist\aws-amplify.js:30:30)
```

**Comment by xosuperpig** [comment]
`aws-amplify` will make http request by API: `fetch` or `XMLHttpRequest`. They are provided by browser environment. 
`puerts` is a script engine and does not provide any network API now.

maybe you could firstly write a mock for `fetch` or `XMLHttpRequest` by C++ and export it to JS environment by puerts. (We probably do this sooner or later but it is not planned by now)

--------------------------

`aws-amplify` 会使用 `fetch` 和 `XMLHttpRequest` 来发起HTTP请求。这两个API默认是浏览器环境提供的。
而`puerts`作为脚本引擎并没有提供这样的网络API

你可以考虑下先用c++写一个`fetch`和`XMLHttpRequest`的模拟，并且用puerts将其暴露给JS环境。（我们以后可能会做这件事，但现在还没有计划）

**Comment by xosuperpig** [comment]
BTW: you saw the error is because there is no `self` variable in global. add these code before your require to solve the error: 
```
global.self = global;
global.window = global;
```

**Comment by Kiddinglife** [comment]
> BTW: you saw the error is because there is no `self` variable in global. add these code before your require to solve the error:
> 
> ```
> global.self = global;
> global.window = global;
> ```

this works. Thank you. 
BTW, can I know what are the advantages of `Puerts` over another similar project `UnrealJS` ?

**Comment by chexiongsheng** [comment]
> > BTW: you saw the error is because there is no `self` variable in global. add these code before your require to solve the error:
> > ```
> > global.self = global;
> > global.window = global;
> > ```
> 
> this works. Thank you.
> BTW, can I know what are the advantages of `Puerts` over another similar project `UnrealJS` ?

Performance  may be better, mobile may be better, typescript support may be better.
And, you can use UE Gameplay framework like [this](https://github.com/chexiongsheng/puerts_fps_demo), when a typescript class extends a  UE class, puerts can auto generate a stub blueprint class, then you can use that typescript class as if it is a blueprint class.
