### ISSUE TITLE
[Unity]  2023 unity支持wasmbigint 开启后puerts无法初始化

### ISSUE THREAD

**Issue by mingxxming** [Tencent/puerts#1798]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unity/zhcn/readme)/[Doc](https://puerts.github.io/unity/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unity/zhcn/faq.md)

### Puer的版本 | Puer Version

2.0.5

### Unity的版本 | Unity Version

2023.2.20f1c1

### 发生在哪个平台 | Platform

Other

### 问题重现 | Bug reproduce

updateGlobalBufferAndViews is not defined
_setTempRet0 is not defined

**Comment by mingxxming** [comment]
_setTempRet:_setTempRet0 改成_setTempRet:setTempRet0 后
(JsEnv 的 PuertsDLL.SetGlobalFunction(isolate, "__tgjsGetLoader", StaticCallbacks.JsEnvCallbackWrap, AddCallback(GetLoader));执行了,貌似没生效)：
TypeError: Cannot read properties of undefined (reading 'Resolve')
at GetModuleExecutor (http://localhost:8000/puerts-runtime.js:1346:46)
    at _GetModuleExecutor (http://localhost:8000/Build/GC_TEST_MOCK_20_30.framework.js:9:22802)
    at JsEnv_ExecuteModule_mAF27EC9BC1E1AFFA74F184745E0768B7714245CF (http://localhost:8000/Build/GC_TEST_MOCK_20_30.wasm:wasm-function[100328]:0x1cf4b6e)
    at emscripten::internal::Invoker<bool, GameWorld*, unsigned int, int>::invoke(bool (*)(GameWorld*, unsigned int, int), GameWorld*, unsigned int, int) (http://localhost:8000/Build/GC_TEST_MOCK_20_30.wasm:wasm-function[65541]:0x133f4e6)
    at invoke_iiii (http://localhost:8000/Build/GC_TEST_MOCK_20_30.framework.js:9:586343)
    at JsEnv__ctor_m97A50DA00BE04FBF977E92A3F3B113F165D1D148 (http://localhost:8000/Build/GC_TEST_MOCK_20_30.wasm:wasm-function[100317]:0x1cf1aac)
    at JsEnv__ctor_mB6BCEF8CD9B830999981B515B0CFC91EFF517928 (http://localhost:8000/Build/GC_TEST_MOCK_20_30.wasm:wasm-function[100330]:0x1cf4ca8)
    at MainEnv_Get_m7D4FE03B876D21E85829F4853DD2D9D48D055977 (http://localhost:8000/Build/GC_TEST_MOCK_20_30.wasm:wasm-function[70585]:0x137eecb)
    at JSManager__ctor_m29A6C23C1B38376CE05B5DA7B61ACFC8EAD90E80 (http://localhost:8000/Build/GC_TEST_MOCK_20_30.wasm:wasm-function[70972]:0x139d8f3)
    at GameInstance__ctor_m552C13A28CAB5F5092D9F8E9827AF4DBF7543154 (http://localhost:8000/Build/GC_TEST_MOCK_20_30.wasm:wasm-function[70970]:0x139d03c)
    at GameLaunch_NewGI_m31FB21A70ABCBA34ABECF3AE1324198D3FE4B806 (http://localhost:8000/Build/GC_TEST_MOCK_20_30.wasm:wasm-function[51824]:0x109408d)
    at U3CInitGameU3Ed__72_MoveNext_mE4AE6D33A43BB61D897B0F74F6DB90AE08C6A80F (http://localhost:8000/Build/GC_TEST_MOCK_20_30.wasm:wasm-function[52079]:0x109e44d)
    at SetupCoroutine_InvokeMoveNext_m72FC77384CAC3133B6EE650E0581D055B34B2F5F (http://localhost:8000/Build/GC_TEST_MOCK_20_30.wasm:wasm-function[129523]:0x24b5ede)

**Comment by mingxxming** [comment]
__tgjsGetLoader ------------ function
console.log("globalThis.__tgjsGetLoader()", globalThis.__tgjsGetLoader(), typeof(globalThis.__tgjsGetLoader())):
globalThis.__tgjsGetLoader() undefined undefined

**Comment by chexiongsheng** [comment]
webgl的问题到这里提：https://github.com/zombieyang/puerts_unity_webgl_demo
