### ISSUE TITLE
[UE] Bug: BlueprintPure Function TypeError: is not a function

### ISSUE THREAD

**Issue by slb1988** [Tencent/puerts#1804]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

1.0.7

### UE的版本 | UE Version

5.4.3

### 发生在哪个平台 | Platform

Android

### 错误信息 | Error Message

[2024.08.01-11.18.18:445][  0]Puerts: Error: (0x0x77dfd7a478) /storage/emulated/0/Android/data/com.Luckey.PuertsDemo/files/UnrealGame/MyProject/MyProject/Content/JavaScript/puerts/modular.js:194: TypeError: ue_1.MyBlueprintFunctionLibrary.GetTimestamp is not a function

TypeError: ue_1.MyBlueprintFunctionLibrary.GetTimestamp is not a function
    at /storage/emulated/0/Android/data/com.Luckey.PuertsDemo/files/UnrealGame/MyProject/MyProject/Content/JavaScript/QuickStart.js:15:45
    at executeModule (/storage/emulated/0/Android/data/com.Luckey.PuertsDemo/files/UnrealGame/MyProject/MyProject/Content/JavaScript/puerts/modular.js:70:9)
    at require (/storage/emulated/0/Android/data/com.Luckey.PuertsDemo/files/UnrealGame/MyProject/MyProject/Content/JavaScript/puerts/modular.js:186:29)

### 问题重现 | Bug reproduce

UBlueprintFunctionLibrary 继承的类 MyBlueprintFunctionLibrary 中，定义如下函数，

	UFUNCTION(BlueprintCallable, BlueprintPure)
	static const int64 GetTimestamp();

在TS中调用，

	console.log(MyBlueprintFunctionLibrary.GetTimestamp())

Editor下正常，但导出Windows、Android都会报 TypeError的错误，作为对比相同的定义，去掉 BlueprintPure 表现正常

**Comment by chexiongsheng** [comment]
我刚在ue5.4，window实测可以，也没听说别人有类似的反馈。
会不会是你另外加了仅编辑器可用的宏或选项？

**Comment by slb1988** [comment]
没有相关宏包裹。 自己反复测试了下确定跟这个函数名有关 GetTimestamp， 改成其它的名字就可以通过了，另外两个条件是 【静态函数】&【标记 BlueprintPure】 。

    UFUNCTION(BlueprintCallable, BlueprintPure)
    static int64 GetTimestamp();

另外自己是源码版引擎构建的，如果想自己排查的话，哪里可以找线索呢，调用的源头是在v8层，请问函数注册那块在哪里可以断点或打日志查看呢（比如 FunctionFlags 过滤之类）？

**Comment by slb1988** [comment]
定义的函数 GetTimestamp 's'是小写，导出到Windows运行时脚本层变成了大写，所以找不到，具体为什么就不太清楚了。。。
我看Q&A里有一段文字，不知道是否相关

    打包后运行时报一些字段找不到
    这大多数是由UE对FName编辑器和运行时处理不一致导致的，默认编辑器下大小写敏感，运行时大小写不敏感。

    打比方，你在蓝图定义了一个count字段，在编辑器下生成代码，这个字段生成为count，运行也正常。

    而打包后，如果在你访问这个蓝图前，已经有另外一个地方初始化了一个“Count”字段，那么你访问这个蓝图时，该字段会     是"Count"，因为FName.ToString返回的是第一次构造该FName输入的字符串，后面只要转成小写后和第一次一样的FName，都    是重用第一次的。

    所以你在脚本访问的count字段会不存在（变成了Count字段）。


[2024.08.06-09.03.09:534][  0]Puerts: (0x0000022719A7B290) ---------------SaveStringToFile
[2024.08.06-09.03.09:534][  0]Puerts: (0x0000022719A7B290) ---------------GetTotalSeconds
[2024.08.06-09.03.09:534][  0]Puerts: (0x0000022719A7B290) ---------------GetTimeStamp
[2024.08.06-09.03.09:534][  0]Puerts: (0x0000022719A7B290) ---------------GetPlatform
[2024.08.06-09.03.09:534][  0]Puerts: (0x0000022719A7B290) ---------------GetBuildConfiguration
[2024.08.06-09.03.09:534][  0]Puerts: (0x0000022719A7B290) ---------------BP_GetTimestamp
[2024.08.06-09.03.09:534][  0]Puerts: (0x0000022719A7B290) ---------------Find
[2024.08.06-09.03.09:534][  0]Puerts: (0x0000022719A7B290) ---------------Load
[2024.08.06-09.03.09:534][  0]Puerts: (0x0000022719A7B290) ---------------StaticClass
[2024.08.06-09.03.09:534][  0]Puerts: Error: (0x0000022719A7B290) Pak: ..\..\..\CustomEditorTools\Content\Paks\CustomEditorTools-Windows.pak\CustomEditorTools\Content\JavaScript\puerts\modular.js:191: TypeError: UE.TestCaseBlueprintFunctionLibrary.GetTimestamp is not a function

TypeError: UE.TestCaseBlueprintFunctionLibrary.GetTimestamp is not a function
    at ..\..\..\CustomEditorTools\Content\JavaScript\Main.js:27:49

**Comment by chexiongsheng** [comment]
就这原因，但按理说v8下有相关的兼容，你用的是v8还是qjs？

**Comment by slb1988** [comment]
v8
