### ISSUE TITLE
[UE] Bug:  FVector_Wrap等代码在UE5中存在精度损失的问题

### ISSUE THREAD

**Issue by BlurryLight** [Tencent/puerts#1904]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

1.0.6

### UE的版本 | UE Version

All

### 发生在哪个平台 | Platform

Editor(mac)

### 问题重现 | Bug reproduce

写一些测试代码的时候发现早期自动生成的这些绑定代码都是存在大量的`float`类型，这里数据存在 `double->float->double`的转换，会丢失精度。
https://github.com/Tencent/puerts/blob/662f93cda5883cd976f675a875f9d0c3c9b23a69/unreal/Puerts/Source/JsEnv/Private/Gen/FVector2D_Wrap.cpp#L64
```
    if (Info.Length() == 2)
    {
        if (Info[0]->IsNumber() && Info[1]->IsNumber())
        {
            float Arg0 = Info[0]->ToNumber(Context).ToLocalChecked()->Value(); //  这里发生了 double -> float 变窄
            float Arg1 = Info[1]->ToNumber(Context).ToLocalChecked()->Value();
            FVector2D* Obj = new FVector2D(Arg0, Arg1);  // 又从 float 自动转到 double，但是精度已经丢了 
```

**Comment by chexiongsheng** [comment]
最好改成模板绑定。

**Comment by BlurryLight** [comment]
这些wrapper感觉都可以用 static binding来代替了..大型体力活

**Comment by chexiongsheng** [comment]
今天把这生成器跑起来了：https://github.com/chexiongsheng/puerts_unreal_demo/tree/master/Plugins/Puerts/Generator
这个依赖的东西都很古老，要求32位的python2，它本身带的clang库也是llvm 8的，window sdk会直接报c++版本过低。

我试试改生成器去生成模板绑定代码。

**Comment by BlurryLight** [comment]
昨天花了大概半个小时用static binding重写了 FVector2D_wrapper的绑定代码，测试下来没啥问题，感觉还是彻底统一到static binding这块比较好。

目前puer ue这边总共有三种binding方式，有点混乱。
- UProperty: property translator
- static binding
- 以及代码生成的一部分v8裸绑定代码

前两种binding的方式都有比较统一的入口，很方便加一些hook操作，比如埋点统计类型之类的，但是最后一种方式要加埋点之类的都很麻烦，想要做池化也很麻烦，应该彻底淘汰掉。

**Comment by BlurryLight** [comment]
后续整理完了PR过来吧

**Comment by chexiongsheng** [comment]
你把调通FVector2D_wrapper代码贴下？
我下周参考着改改生成器。

**Comment by BlurryLight** [comment]
```diff
diff --git a/Plugins/Puerts/Source/JsEnv/Private/Gen/FVector2D_Wrap.cpp b/Plugins/Puerts/Source/JsEnv/Private/Gen/FVector2D_Wrap.cpp
index 13d1ae1..77c1520 100644
--- a/Plugins/Puerts/Source/JsEnv/Private/Gen/FVector2D_Wrap.cpp
+++ b/Plugins/Puerts/Source/JsEnv/Private/Gen/FVector2D_Wrap.cpp
@@ -12,6 +12,7 @@
 #include "CoreMinimal.h"
 #include "DataTransfer.h"
 #include "JSClassRegister.h"
+#include "UEDataBinding.hpp"
 
 // <SourceLocation file 'D:\\Program Files\\Epic Games\\UE_4.24\\Engine\\Source\\Runtime\\Core\\Public\\Math/Vector2D.h', line 207,
 // column 7> unsupported method : operator< bool (const FVector2D &) __attribute__((thiscall)) const
@@ -1404,46 +1405,182 @@
     Self->Y = Value->ToNumber(Context).ToLocalChecked()->Value();
 }
 
+// struct AutoRegisterForFVector2D
+// {
+//     AutoRegisterForFVector2D()
+//     {
+//         PUERTS_NAMESPACE::JSClassDefinition Def = JSClassEmptyDefinition;
+//
+//         static PUERTS_NAMESPACE::JSPropertyInfo Properties[] = {
+//             {"X", _FVector2DXGet_, _FVector2DXSet_}, {"Y", _FVector2DYGet_, _FVector2DYSet_}, {0, 0, 0}};
+//
+//         static PUERTS_NAMESPACE::JSFunctionInfo Methods[] = {{"op_Addition", FVector2DM_op_Addition},
+//             {"op_Subtraction", FVector2DM_op_Subtraction}, {"op_Multiply", FVector2DM_op_Multiply},
+//             {"op_Division", FVector2DM_op_Division}, {"op_BitwiseOr", FVector2DM_op_BitwiseOr},
+//             {"op_ExclusiveOr", FVector2DM_op_ExclusiveOr}, {"op_Equality", FVector2DM_op_Equality},
+//             {"op_Inequality", FVector2DM_op_Inequality}, {"op_UnaryNegation", FVector2DM_op_UnaryNegation},
+//             {"set_Item", FVector2DM_set_Item}, {"get_Item", FVector2DM_get_Item}, {"Component", FVector2DM_Component},
+//             {"Equals", FVector2DM_Equals}, {"Set", FVector2DM_Set}, {"GetMax", FVector2DM_GetMax},
+//             {"GetAbsMax", FVector2DM_GetAbsMax}, {"GetMin", FVector2DM_GetMin}, {"Size", FVector2DM_Size},
+//             {"SizeSquared", FVector2DM_SizeSquared}, {"GetRotated", FVector2DM_GetRotated},
+//             {"GetSafeNormal", FVector2DM_GetSafeNormal}, {"Normalize", FVector2DM_Normalize},
+//             {"IsNearlyZero", FVector2DM_IsNearlyZero}, {"ToDirectionAndLength", FVector2DM_ToDirectionAndLength},
+//             {"IsZero", FVector2DM_IsZero}, {"IntPoint", FVector2DM_IntPoint}, {"RoundToVector", FVector2DM_RoundToVector},
+//             {"ClampAxes", FVector2DM_ClampAxes}, {"GetSignVector", FVector2DM_GetSignVector}, {"GetAbs", FVector2DM_GetAbs},
+//             {"ToString", FVector2DM_ToString}, {"InitFromString", FVector2DM_InitFromString},
+//             {"DiagnosticCheckNaN", FVector2DM_DiagnosticCheckNaN}, {"ContainsNaN", FVector2DM_ContainsNaN},
+//             {"SphericalToUnitCartesian", FVector2DM_SphericalToUnitCartesian}, {0, 0}};
+//
+//         static PUERTS_NAMESPACE::JSFunctionInfo Functions[] = {{"DotProduct", FVector2DS_DotProduct},
+//             {"DistSquared", FVector2DS_DistSquared}, {"Distance", FVector2DS_Distance}, {"CrossProduct", FVector2DS_CrossProduct},
+//             {0, 0}};
+//
+//         Def.UETypeName = "Vector2D";
+//
+//         Def.SetInitialize(_FVector2DNew_);
+//         Def.Finalize = _FVector2DDelete_;
+//         Def.Properties = Properties;
+//         Def.Methods = Methods;
+//         Def.Functions = Functions;
+//
+//         PUERTS_NAMESPACE::RegisterJSClass(Def);
+//     }
+// };
+//
+
+UsingUStruct(FVector2d);
+UsingUStruct(FVector);
+UsingUStruct(FVector4);
+UsingUStruct(FIntPoint);
+
+struct FVector2DExtension
+{
+    static FVector2D op_Addition(const FVector2D& self, const FVector2D& V)
+    {
+        return self + V;
+    }
+
+    static FVector2D op_Subtraction(const FVector2D& self, const FVector2D& V)
+    {
+        return self - V;
+    }
+
+    static FVector2D op_Multiply(const FVector2D& self, const FVector2D& V)
+    {
+        return self * V;
+    }
+
+    static FVector2D op_Division(const FVector2D& self, const FVector2D& V)
+    {
+        return self / V;
+    }
+
+    static double op_BitwiseOr(const FVector2D& self, const FVector2D& V)
+    {
+        return self | V;
+    }
+
+    static double op_ExclusiveOr(const FVector2D& self, const FVector2D& V)
+    {
+        return self ^ V;
+    }
+
+    static bool op_Equality(const FVector2D& self, const FVector2D& V)
+    {
+        return self == V;
+    }
+
+    static bool op_Inequality(const FVector2D& self, const FVector2D& V)
+    {
+        return self != V;
+    }
+
+    static FVector2D op_UnaryNegation(const FVector2D& self)
+    {
+        return -self;
+    }
+
+    static double get_Item(const FVector2D& self, int32 Index)
+    {
+        return self[Index];
+    }
+
+    static void set_Item(FVector2D& self, int32 Index, double Value)
+    {
+        self[Index] = Value;
+    }
+
+    static double Component(const FVector2D& self, int32 Index)
+    {
+        return self.Component(Index);
+    }
+
+    static void ToDirectionAndLength(const FVector2D& self, FVector2D& OutDir, double& OutLength)
+    {
+        self.ToDirectionAndLength(OutDir, OutLength);
+    }
+};
+
 struct AutoRegisterForFVector2D
 {
     AutoRegisterForFVector2D()
     {
-        PUERTS_NAMESPACE::JSClassDefinition Def = JSClassEmptyDefinition;
-
-        static PUERTS_NAMESPACE::JSPropertyInfo Properties[] = {
-            {"X", _FVector2DXGet_, _FVector2DXSet_}, {"Y", _FVector2DYGet_, _FVector2DYSet_}, {0, 0, 0}};
-
-        static PUERTS_NAMESPACE::JSFunctionInfo Methods[] = {{"op_Addition", FVector2DM_op_Addition},
-            {"op_Subtraction", FVector2DM_op_Subtraction}, {"op_Multiply", FVector2DM_op_Multiply},
-            {"op_Division", FVector2DM_op_Division}, {"op_BitwiseOr", FVector2DM_op_BitwiseOr},
-            {"op_ExclusiveOr", FVector2DM_op_ExclusiveOr}, {"op_Equality", FVector2DM_op_Equality},
-            {"op_Inequality", FVector2DM_op_Inequality}, {"op_UnaryNegation", FVector2DM_op_UnaryNegation},
-            {"set_Item", FVector2DM_set_Item}, {"get_Item", FVector2DM_get_Item}, {"Component", FVector2DM_Component},
-            {"Equals", FVector2DM_Equals}, {"Set", FVector2DM_Set}, {"GetMax", FVector2DM_GetMax},
-            {"GetAbsMax", FVector2DM_GetAbsMax}, {"GetMin", FVector2DM_GetMin}, {"Size", FVector2DM_Size},
-            {"SizeSquared", FVector2DM_SizeSquared}, {"GetRotated", FVector2DM_GetRotated},
-            {"GetSafeNormal", FVector2DM_GetSafeNormal}, {"Normalize", FVector2DM_Normalize},
-            {"IsNearlyZero", FVector2DM_IsNearlyZero}, {"ToDirectionAndLength", FVector2DM_ToDirectionAndLength},
-            {"IsZero", FVector2DM_IsZero}, {"IntPoint", FVector2DM_IntPoint}, {"RoundToVector", FVector2DM_RoundToVector},
-            {"ClampAxes", FVector2DM_ClampAxes}, {"GetSignVector", FVector2DM_GetSignVector}, {"GetAbs", FVector2DM_GetAbs},
-            {"ToString", FVector2DM_ToString}, {"InitFromString", FVector2DM_InitFromString},
-            {"DiagnosticCheckNaN", FVector2DM_DiagnosticCheckNaN}, {"ContainsNaN", FVector2DM_ContainsNaN},
-            {"SphericalToUnitCartesian", FVector2DM_SphericalToUnitCartesian}, {0, 0}};
-
-        static PUERTS_NAMESPACE::JSFunctionInfo Functions[] = {{"DotProduct", FVector2DS_DotProduct},
-            {"DistSquared", FVector2DS_DistSquared}, {"Distance", FVector2DS_Distance}, {"CrossProduct", FVector2DS_CrossProduct},
-            {0, 0}};
-
-        Def.UETypeName = "Vector2D";
-
-        Def.SetInitialize(_FVector2DNew_);
-        Def.Finalize = _FVector2DDelete_;
-        Def.Properties = Properties;
-        Def.Methods = Methods;
-        Def.Functions = Functions;
-
-        PUERTS_NAMESPACE::RegisterJSClass(Def);
+        puerts::DefineClass<FVector2d>()
+        .Constructor(
+            CombineConstructors(
+                MakeConstructor(FVector2d),
+                MakeConstructor(FVector2d,double,double),
+                MakeConstructor(FVector2d,double),
+                MakeConstructor(FVector2d,FVector),
+                MakeConstructor(FVector2d,FVector4),
+                MakeConstructor(FVector2d,FIntPoint)
+           )
+        )
+        .Property("X", MakeProperty(&FVector2d::X))
+        .Property("Y", MakeProperty(&FVector2d::Y))
+        .Function("DotProduct", MakeFunction(&FVector2d::DotProduct))
+        .Function("DistSquared", MakeFunction(&FVector2d::DistSquared))
+        .Function("Distance", MakeFunction(&FVector2d::Distance))
+        .Function("CrossProduct", MakeFunction(&FVector2d::CrossProduct))
+        .Method("Equals", MakeFunction(&FVector2d::Equals, UE_KINDA_SMALL_NUMBER))
+        .Method("GetMax", MakeFunction(&FVector2d::GetMax))
+        .Method("GetAbsMax", MakeFunction(&FVector2d::GetAbsMax))
+        .Method("GetMin", MakeFunction(&FVector2d::GetMin))
+        .Method("Size", MakeFunction(&FVector2d::Size))
+        .Method("SizeSquared", MakeFunction(&FVector2d::SizeSquared))
+        .Method("GetRotated", MakeFunction(&FVector2d::GetRotated))
+        .Method("GetSafeNormal", MakeFunction(&FVector2d::GetSafeNormal, UE_SMALL_NUMBER))
+        .Method("Normalize", MakeFunction(&FVector2d::Normalize, UE_SMALL_NUMBER))
+        .Method("IsNearlyZero", MakeFunction(&FVector2d::IsNearlyZero, UE_SMALL_NUMBER))
+        // .Method("ToDirectionAndLength", SelectFunction(void(FVector2d::*)(FVector2d&, double&),&FVector2d::ToDirectionAndLength))
+        .Method("IsZero", MakeFunction(&FVector2d::IsZero))
+        .Method("IntPoint", MakeFunction(&FVector2d::IntPoint))
+        .Method("RoundToVector", MakeFunction(&FVector2d::RoundToVector))
+        .Method("ClampAxes", MakeFunction(&FVector2d::ClampAxes))
+        .Method("GetSignVector", MakeFunction(&FVector2d::GetSignVector))
+        .Method("GetAbs", MakeFunction(&FVector2d::GetAbs))
+        .Method("ToString", MakeFunction(&FVector2d::ToString))
+        .Method("InitFromString", MakeFunction(&FVector2d::InitFromString))
+        .Method("DiagnosticCheckNaN", MakeFunction(&FVector2d::DiagnosticCheckNaN))
+        .Method("ContainsNaN", MakeFunction(&FVector2d::ContainsNaN))
+        .Method("SphericalToUnitCartesian", MakeFunction(&FVector2d::SphericalToUnitCartesian))
+        
+        .Method("op_Addition", MakeExtension(&FVector2DExtension::op_Addition))
+        .Method("op_Subtraction", MakeExtension(&FVector2DExtension::op_Subtraction))
+        .Method("op_Multiply", MakeExtension(&FVector2DExtension::op_Multiply))
+        .Method("op_Division", MakeExtension(&FVector2DExtension::op_Division))
+        .Method("op_BitwiseOr", MakeExtension(&FVector2DExtension::op_BitwiseOr))
+        .Method("op_ExclusiveOr", MakeExtension(&FVector2DExtension::op_ExclusiveOr))
+        .Method("op_Equality", MakeExtension(&FVector2DExtension::op_Equality))
+        .Method("op_Inequality", MakeExtension(&FVector2DExtension::op_Inequality))
+        .Method("op_UnaryNegation", MakeExtension(&FVector2DExtension::op_UnaryNegation))
+        .Method("get_Item", MakeExtension(&FVector2DExtension::get_Item))
+        .Method("set_Item", MakeExtension(&FVector2DExtension::set_Item))
+        .Method("Component", MakeExtension(&FVector2DExtension::Component))
+        .Method("ToDirectionAndLength", MakeExtension(&FVector2DExtension::ToDirectionAndLength))
+        
+        .Register();
     }
 };
 
```

大量用了扩展方法来包装函数是因为 1. cpp不允许拿operator的函数指针 2. 部分有函数重载的用SelectFunction怎么都有编译报错不得不自己包一层..

**Comment by chexiongsheng** [comment]
这里有操作符重载SelectFunction
https://github.com/Tencent/puerts/blob/master/unreal/Puerts/Source/JsEnv/Public/UEDataBinding.hpp#L76
其实我昨天晚上也搞到重载那里了，也报错，太晚就回家了。
ue5.4的FVector2D用模板实现了，感觉和这个有关，试试参考这的TArray的例子？SelectFunction的函数签名得用实例化的模板而不能用typedef的名字？

**Comment by BlurryLight** [comment]
好像找到原因了，部分函数签名有const就会匹配不上，我改了一下试试

**Comment by chexiongsheng** [comment]
更正下，和模板实现没关，和我在ue4.24生成（生成工具只支持4.24及以下），有些函数的签名声明成float了。

**Comment by BlurryLight** [comment]
UE5 以后为了支持大世界，FVector之类的数据类型被重新typedef了一部分，以前有的是float，后面变成了double

**Comment by BlurryLight** [comment]
更正一版可以用的 FVector2D的 static binding
```cpp
struct AutoRegisterForFVector2D
{
    AutoRegisterForFVector2D()
    {
        // void (UE::Math::TVector2<double>::* Func)(UE::Math::TVector2<double>&, double&) const = &UE::Math::TVector2<double>::ToDirectionAndLength;
        FVector2d (UE::Math::TVector2<double>::* Func)(void) const = &UE::Math::TVector2<double>::operator-;

        puerts::DefineClass<FVector2d>()
        .Constructor(
            CombineConstructors(
                MakeConstructor(FVector2d),
                MakeConstructor(FVector2d,double,double),
                MakeConstructor(FVector2d,double),
                MakeConstructor(FVector2d,FVector),
                MakeConstructor(FVector2d,FVector4),
                MakeConstructor(FVector2d,FIntPoint)
           )
        )
        .Property("X", MakeProperty(&FVector2d::X))
        .Property("Y", MakeProperty(&FVector2d::Y))
        .Function("DotProduct", MakeFunction(&FVector2d::DotProduct))
        .Function("DistSquared", MakeFunction(&FVector2d::DistSquared))
        .Function("Distance", MakeFunction(&FVector2d::Distance))
        .Function("CrossProduct", MakeFunction(&FVector2d::CrossProduct))
        .Method("Equals", MakeFunction(&FVector2d::Equals, UE_KINDA_SMALL_NUMBER))
        .Method("GetMax", MakeFunction(&FVector2d::GetMax))
        .Method("GetAbsMax", MakeFunction(&FVector2d::GetAbsMax))
        .Method("GetMin", MakeFunction(&FVector2d::GetMin))
        .Method("Size", MakeFunction(&FVector2d::Size))
        .Method("SizeSquared", MakeFunction(&FVector2d::SizeSquared))
        .Method("GetRotated", MakeFunction(&FVector2d::GetRotated))
        .Method("GetSafeNormal", MakeFunction(&FVector2d::GetSafeNormal, UE_SMALL_NUMBER))
        .Method("Normalize", MakeFunction(&FVector2d::Normalize, UE_SMALL_NUMBER))
        .Method("IsNearlyZero", MakeFunction(&FVector2d::IsNearlyZero, UE_SMALL_NUMBER))
        .Method("ToDirectionAndLength", SelectFunction(void(FVector2d::*)(FVector2d&, double&) const,&FVector2d::ToDirectionAndLength))
        .Method("Component", SelectFunction(double(FVector2d::*)(int32) const,&FVector2d::Component))
        .Method("IsZero", MakeFunction(&FVector2d::IsZero))
        .Method("IntPoint", MakeFunction(&FVector2d::IntPoint))
        .Method("RoundToVector", MakeFunction(&FVector2d::RoundToVector))
        .Method("ClampAxes", MakeFunction(&FVector2d::ClampAxes))
        .Method("GetSignVector", MakeFunction(&FVector2d::GetSignVector))
        .Method("GetAbs", MakeFunction(&FVector2d::GetAbs))
        .Method("ToString", MakeFunction(&FVector2d::ToString))
        .Method("InitFromString", MakeFunction(&FVector2d::InitFromString))
        .Method("DiagnosticCheckNaN", MakeFunction(&FVector2d::DiagnosticCheckNaN))
        .Method("ContainsNaN", MakeFunction(&FVector2d::ContainsNaN))
        .Method("SphericalToUnitCartesian", MakeFunction(&FVector2d::SphericalToUnitCartesian))
        
        .Method("op_Addition", CombineOverloads(
            MakeOverload(FVector2d (FVector2d::*)(const FVector2d&) const,&FVector2d::operator+),
            MakeOverload(FVector2d (FVector2d::*)(double)const,&FVector2d::operator+)
        ))
        .Method("op_Subtraction", CombineOverloads(
            MakeOverload(FVector2d (FVector2d::*)(const FVector2d&) const,&FVector2d::operator-),
            MakeOverload(FVector2d (FVector2d::*)(double)const,&FVector2d::operator-)
        ))
        .Method("op_Multiply", CombineOverloads(
            MakeOverload(FVector2d (FVector2d::*)(const FVector2d&) const,&FVector2d::operator*),
            MakeOverload(FVector2d (FVector2d::*)(double)const,&FVector2d::operator*)
        ))
        .Method("op_Division", CombineOverloads(
            MakeOverload(FVector2d (FVector2d::*)(const FVector2d&) const,&FVector2d::operator/),
            MakeOverload(FVector2d (FVector2d::*)(double)const,&FVector2d::operator/)
        ))
        .Method("op_BitwiseOr", MakeFunction(&FVector2d::operator|))
        .Method("op_ExclusiveOr", MakeFunction(&FVector2d::operator^))
        
        .Method("op_Equality", MakeFunction(&FVector2D::operator==))
        .Method("op_Inequality", MakeFunction(&FVector2D::operator!=))
        .Method("op_UnaryNegation", SelectFunction(FVector2d (FVector2d::*)(void)const, &FVector2D::operator-))
        .Method("get_Item", SelectFunction(double (FVector2d::*)(int32)const, &FVector2D::operator[]))
        .Method("set_Item", SelectFunction(double& (FVector2d::*)(int32), &FVector2D::operator[]))
        
        .Register();
    }
};
```

**Comment by chexiongsheng** [comment]
我这的生成的FVector也能用，不过的手工修复一下，FVector要手工修的主要是类型从float修改为double，得用宏判断下才能兼容各ue版本，另外是ue4.24有些函数只有一个，生成时没有MakeOverload

**Comment by chexiongsheng** [comment]
调通了，然后格式化搞坏了

**Comment by BlurryLight** [comment]
`ue_s.d.ts`需要更新么，还是说签名都是和之前兼容的。之前有一些

**Comment by BlurryLight** [comment]
https://github.com/Tencent/puerts/commit/9d62ee358bc3c22a3ed376823802ace602104909

`operator-`编译报错我也碰到了，感觉和vs的版本有关系。取函数指针的时候加一个括号括一下，不然会和模板的尖括号形成 `operator- >`然后提示找不到这个符号

**Comment by chexiongsheng** [comment]
operator-加括号clang编译会报错，我通过在模板实例化那多输入一个参数避免了`operator- >`。
我已经提交了，4.27各平台的ci都编译通过了。

**Comment by BlurryLight** [comment]
https://github.com/Tencent/puerts/commit/23dd521489929e22cc914162d4af7d6890fcbe46
发现按UStruct来生成的.d.ts的话部分静态绑定的函数没生成对应的声明。

这个是生成的绑定代码

```cpp
       puerts::DefineClass<FVector>()
            .Constructor(CombineConstructors(MakeConstructor(FVector), MakeConstructor(FVector, float),
                MakeConstructor(FVector, float, float, float), MakeConstructor(FVector, const FVector2D, float),
                MakeConstructor(FVector, const FVector4&), MakeConstructor(FVector, const FLinearColor&),
                MakeConstructor(FVector, FIntVector), MakeConstructor(FVector, FIntPoint), MakeConstructor(FVector, EForceInit)))
```

这个是生成的.d.ts

```
    class Vector {
        constructor();
        constructor(X: number, Y: number, Z: number);
        X: number;
        Y: number;
        Z: number;
        AddBounded(p0: Vector, p1: number) : void;
```

漏了好几个构造函数

**Comment by BlurryLight** [comment]
这样补充一下应该就可以了
```patch
Subject: [PATCH] find missing constructor
---
Index: Plugins/Puerts/Source/DeclarationGenerator/Private/DeclarationGenerator.cpp
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/Plugins/Puerts/Source/DeclarationGenerator/Private/DeclarationGenerator.cpp b/Plugins/Puerts/Source/DeclarationGenerator/Private/DeclarationGenerator.cpp
--- a/Plugins/Puerts/Source/DeclarationGenerator/Private/DeclarationGenerator.cpp	(revision 50dc062d48065b45ec5a28512f36f3958910f282)
+++ b/Plugins/Puerts/Source/DeclarationGenerator/Private/DeclarationGenerator.cpp	(date 1731464495538)
@@ -1432,6 +1432,23 @@
         if (HasProperty)
             StringBuffer << "    constructor();\n";
         StringBuffer << "    " << TmpBuff.Buffer << ";\n";
+        
+        TmpBuff.Buffer.Reset();
+        auto ClassDefinition = PUERTS_NAMESPACE::FindClassByType(Struct);
+        if (ClassDefinition)
+        {
+            PUERTS_NAMESPACE::NamedFunctionInfo* ConstructInfo = ClassDefinition->ConstructorInfos;
+            while (ConstructInfo && ConstructInfo->Name && ConstructInfo->Type)
+            {
+                FStringBuffer Tmp;
+                TmpBuff << ConstructInfo->Name << "(";
+                GenArgumentsForFunctionInfo(ConstructInfo->Type, TmpBuff);
+                TmpBuff << ");\n";
+                ++ConstructInfo;
+            }
+        }
+        StringBuffer << TmpBuff.Buffer;
+        
     };
     GenConstrutor();
 
```

**Comment by BlurryLight** [comment]
还有新的问题，
1. 可能会生成没有静态绑定的类型的构造函数，比如FLinearColor有一个 `Float16Color`的构造函数，而`Float16Color` 没有导出静态绑定，会找不到类型。
2. 混合上TArray以后签名不对，这里应该是`UE.TArray<Vector2D>`
![image](https://github.com/user-attachments/assets/79ee62f9-c3f6-4232-8355-aa6e47c9dfcf)

**Comment by chexiongsheng** [comment]
TArray解决了，Float16Color在看怎么获取。

**Comment by chexiongsheng** [comment]
更新下

**Comment by BlurryLight** [comment]
发现另外一个bug case，没定位到原因，车神帮忙看看，目测是哪个converter类型没匹配上。

测试脚本
```ts
import * as ue from 'ue'

for (let i = 0; i < 10000; i++) {

  let localX = Math.random() * 2 - 1;
  let localY = Math.random() * 2 - 1;

  let p = new ue.IntPoint(Math.round(localX), Math.round(localY));
}
```

有几率抛异常

```
LogOutputDevice: Error: Ensure condition failed: false [File:C:\coderepo\third_person\Plugins\Puerts\Source\JsEnv\Public\StaticCall.hpp] [Line: 1117] 
Argument Check failed
LogStats:             FDebug::EnsureFailed -  0.000 s
Puerts: Error: (0x00000ABF45FA6930) C:\coderepo\third_person\Content\JavaScript\puerts\modular.js:191: Error: invalid parameter!
Error: invalid parameter!
    at C:\coderepo\third_person\Content\JavaScript\TestIntPoint.js:8:13
    at executeModule (C:\coderepo\third_person\Content\JavaScript\puerts\modular.js:70:9)
    at require (C:\coderepo\third_person\Content\JavaScript\puerts\modular.js:183:29)
```

加了点日志，发现是这里没通过，但是没看出来为啥通过不了。
![image](https://github.com/user-attachments/assets/3ca68b93-41e4-4a51-830b-bcbd7eb539a0)

**Comment by chexiongsheng** [comment]
> 发现另外一个bug case，没定位到原因，车神帮忙看看，目测是哪个converter类型没匹配上。
> 
> 测试脚本
> 
> ```ts
> import * as ue from 'ue'
> 
> for (let i = 0; i < 10000; i++) {
> 
>   let localX = Math.random() * 2 - 1;
>   let localY = Math.random() * 2 - 1;
> 
>   let p = new ue.IntPoint(Math.round(localX), Math.round(localY));
> }
> ```
> 
> 有几率抛异常
> 
> ```
> LogOutputDevice: Error: Ensure condition failed: false [File:C:\coderepo\third_person\Plugins\Puerts\Source\JsEnv\Public\StaticCall.hpp] [Line: 1117] 
> Argument Check failed
> LogStats:             FDebug::EnsureFailed -  0.000 s
> Puerts: Error: (0x00000ABF45FA6930) C:\coderepo\third_person\Content\JavaScript\puerts\modular.js:191: Error: invalid parameter!
> Error: invalid parameter!
>     at C:\coderepo\third_person\Content\JavaScript\TestIntPoint.js:8:13
>     at executeModule (C:\coderepo\third_person\Content\JavaScript\puerts\modular.js:70:9)
>     at require (C:\coderepo\third_person\Content\JavaScript\puerts\modular.js:183:29)
> ```
> 
> 加了点日志，发现是这里没通过，但是没看出来为啥通过不了。 ![image](https://private-user-images.githubusercontent.com/14940338/386035652-3ca68b93-41e4-4a51-830b-bcbd7eb539a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NTYzMjUsIm5iZiI6MTczMTU1NjAyNSwicGF0aCI6Ii8xNDk0MDMzOC8zODYwMzU2NTItM2NhNjhiOTMtNDFlNC00YTUxLTgzMGItYmNiZDdlYjUzOWEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDAzNDcwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyYjM0ZTNlODZkMDAyZjcwZDZiY2RkMGFlMWFhZmMzZGRmMjZkZGZmNjVlNjRkYmE0NTY1MjBiYjRlMGZkN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ctQ5G8olI45KvcT909_1S15fsQjAwrgMHtzZNJJ9zBQ)

另外开个issue？
