### ISSUE TITLE
[UE] static binding: ue.IntPoint constructor  有几率触发 invalid parameter

### ISSUE THREAD

**Issue by BlurryLight** [Tencent/puerts#1910]
发现另外一个bug case，没定位到原因，车神帮忙看看，目测是哪个converter类型没匹配上。

测试脚本
```ts
import * as ue from 'ue'

for (let i = 0; i < 10000; i++) {

  let localX = Math.random() * 2 - 1;
  let localY = Math.random() * 2 - 1;

  let p = new ue.IntPoint(Math.round(localX), Math.round(localY));
}
```

有几率抛异常

```
LogOutputDevice: Error: Ensure condition failed: false [File:C:\coderepo\third_person\Plugins\Puerts\Source\JsEnv\Public\StaticCall.hpp] [Line: 1117] 
Argument Check failed
LogStats:             FDebug::EnsureFailed -  0.000 s
Puerts: Error: (0x00000ABF45FA6930) C:\coderepo\third_person\Content\JavaScript\puerts\modular.js:191: Error: invalid parameter!
Error: invalid parameter!
    at C:\coderepo\third_person\Content\JavaScript\TestIntPoint.js:8:13
    at executeModule (C:\coderepo\third_person\Content\JavaScript\puerts\modular.js:70:9)
    at require (C:\coderepo\third_person\Content\JavaScript\puerts\modular.js:183:29)
```

加了点日志，发现是这里没通过，但是没看出来为啥通过不了。
![image](https://github.com/user-attachments/assets/3ca68b93-41e4-4a51-830b-bcbd7eb539a0)

_Originally posted by @BlurryLight in https://github.com/Tencent/puerts/issues/1904#issuecomment-2475353143_

**Comment by chexiongsheng** [comment]
try catch一下，报错时打印下参数？

**Comment by BlurryLight** [comment]
这里估计还要把accept的条件放宽松一点，math.round发挥的应该是number类型？ 不清楚v8内部的实现

**Comment by chexiongsheng** [comment]
这问题有点神奇，我在accpet做了打印
```
    static bool accept(v8::Local<v8::Context> context, const v8::Local<v8::Value>& value)
    {
        if (!value->IsInt32())
        {
            UE_LOG(LogTemp, Warning, TEXT("accept %d, %d, %d"), value->IsNumber(), value->IsUint32(), value->Int32Value(context).ToChecked());
        }
        return value->IsInt32();
    }
```
发现IsNumber()是true，而且值是0。
然后我用字面值0是必定能过的。
而Math.round返回的0也不是必定不过，而是几率不过。。
我的测试代码
```
for (let i = 0; i < 10000; i++) {

  let localX = Math.random() * 2 - 1;
  let localY = Math.random() * 2 - 1;
  let x = Math.round(localX);
  let y = Math.round(localY);

  
  let p = new ue.IntPoint(0, 0);

  console.log(p.ToString(), x, y);
  
  try {
  let p = new ue.IntPoint(x, y);
  }
  catch (e) {
    console.log(`x = ${x}, y = ${y}, e = ${e}`);
    throw e;
  }
}
```
然后一次的输出是：
```
Puerts: (0x0000042877D17B50) X=0 Y=0,1,0
Puerts: (0x0000042877D17B50) X=0 Y=0,1,1
Puerts: (0x0000042877D17B50) X=0 Y=0,0,0
Puerts: (0x0000042877D17B50) X=0 Y=0,0,0
LogTemp: Warning: accept 1, 0, 0
Puerts: (0x0000042877D17B50) x = 0, y = 0, e = Error: invalid parameter!
```
可以看到签名4次循环，尽管Math.round返回0，也能过。

**Comment by chexiongsheng** [comment]
看v8代码IsInt32的实现
```
bool Value::IsInt32() const {
  i::Object obj = *Utils::OpenHandle(this);
  if (obj.IsSmi()) return true;
  if (obj.IsNumber()) {
    return i::IsInt32Double(obj.Number());
  }
  return false;
}

bool IsInt32Double(double value) {
  return value >= kMinInt && value <= kMaxInt && !IsMinusZero(value) &&
         value == FastI2D(FastD2I(value));
}
```
里面有个`!IsMinusZero(value)`，我猜是这里
写代码验证
```
console.log('+0');
let p = new ue.IntPoint(Math.round(0.1), 0);
console.log('-0');
p = new ue.IntPoint(Math.round(-0.1), 0);
```
第二个new那抛异常，确实如此

**Comment by chexiongsheng** [comment]
我感觉我调用IsInt32并没问题。是v8这块的处理会让人困惑（Math.round会返回-0，但IsInt32不认为这是整数），当然我也没从标准那查到这块有没不对的地方。

**Comment by chexiongsheng** [comment]
我个人是建议你们先修改下算法来规避这问题。正数round了后再减。

**Comment by BlurryLight** [comment]
https://stackoverflow.com/a/53135516

```
-0 + 0 = +0
``` 

不清楚v8为什么这么设计，从stackoverflow找了一个很丑的写法来绕过这个问题。

**Comment by zhaojunmeng** [comment]
是不是因为-0是HeapNumber？不是SMI

>  -Infinity // HeapNumber
-(2**30)-1 // HeapNumber
  -(2**30) // Smi
       -42 // Smi
        -0 // HeapNumber
         0 // Smi
       4.2 // HeapNumber
        42 // Smi
   2**30-1 // Smi
     2**30 // HeapNumber
  Infinity // HeapNumber
       NaN // HeapNumber

参考：
https://v8.dev/blog/react-cliff

**Comment by chexiongsheng** [comment]
附上accept那不能改的原因：如果放宽重载就区分不了Foo(int a), Foo(float a)
