### ISSUE TITLE
[UE] Bug: UE5.5无法生成VSProject file

### ISSUE THREAD

**Issue by fengzehua** [Tencent/puerts#1939]
### 前置阅读 | Pre-reading

- [X] [文档](https://puerts.github.io/unreal/zhcn/readme)/[Doc](https://puerts.github.io/unreal/en/readme)
- [X] [Issues](https://github.com/Tencent/puerts/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)
- [X] [FAQ](https://github.com/Tencent/puerts/blob/master/doc/unreal/zhcn/faq.md)

### Puer的版本 | Puer Version

master 24.12.06

### UE的版本 | UE Version

5.5

### 发生在哪个平台 | Platform

Editor(win)

### 错误信息 | Error Message

Unable to parse F:\HMS\HMS_02\Plugins\Puerts\Source\CSharpParamDefaultValueMetas\CSharpParamDefaultValueMetas.ubtplugin.csproj: EpicGames.Core.CsProjectParseException: Error parsing F:\HMS\HMS_02\Plugins\Puerts\Source\CSharpParamDefaultValueMetas\CSharpParamDefaultValueMetas.ubtplugin.csproj: Unable to parse token '$([System.IO.File]::ReadAllText("$(EngineDir)\Build\Build.version"))'

 ---> System.Exception: Unable to parse token '$([System.IO.File]::ReadAllText("$(EngineDir)\Build\Build.version"))'

   at EpicGames.Core.CsProjectInfo.ExpandProperties(String text, Dictionary`2 properties) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\Shared\EpicGames.Core\CsProjectInfo.cs:line 1041

   at EpicGames.Core.CsProjectInfo.ParsePropertyGroup(XmlElement parentElement, CsProjectInfo projectInfo) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\Shared\EpicGames.Core\CsProjectInfo.cs:line 515

   at EpicGames.Core.CsProjectInfo.ParseNode(XmlNode node, CsProjectInfo projectInfo) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\Shared\EpicGames.Core\CsProjectInfo.cs:line 366

   at EpicGames.Core.CsProjectInfo.TryRead(FileReference file, Dictionary`2 properties, CsProjectInfo& outProjectInfo) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\Shared\EpicGames.Core\CsProjectInfo.cs:line 429

   --- End of inner exception stack trace ---

   at EpicGames.Core.CsProjectInfo.TryRead(FileReference file, Dictionary`2 properties, CsProjectInfo& outProjectInfo) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\Shared\EpicGames.Core\CsProjectInfo.cs:line 433

   at UnrealBuildTool.VCSharpProjectFile.GetProjectInfo(UnrealTargetConfiguration InConfiguration) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\ProjectFiles\VisualStudio\VCProject.cs:line 2656

   at UnrealBuildTool.VCSharpProjectFile.IsDotNETCoreProject() in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\ProjectFiles\VisualStudio\VCProject.cs:line 2669

   at UnrealBuildTool.VCSharpProjectFile..ctor(FileReference InitFilePath, ILogger Logger, DirectoryReference BaseDir) in D:\build\++UE5\Sync\Engine\Saved\CsTools\Engine\Source\Programs\UnrealBuildTool\ProjectFiles\VisualStudio\VCProject.cs:line 2558
Total execution time: 3.95 seconds
Existing C# project F:\HMS\HMS_02\Plugins\Puerts\Source\CSharpParamDefaultValueMetas\CSharpParamDefaultValueMetas.ubtplugin.csproj must contain a Debug configuration

### 问题重现 | Bug reproduce

UE5.5无法生成VSProject file

**Comment by chexiongsheng** [comment]
更新这个commit：https://github.com/Tencent/puerts/commit/51e2d0885333d76b9b6b478be036bb3fdddd1eb0

**Comment by chexiongsheng** [comment]
更新这个commit：https://github.com/Tencent/puerts/commit/51e2d0885333d76b9b6b478be036bb3fdddd1eb0
