### ISSUE TITLE
(Unreal) UE[type.symbol.getName(...)].StaticClass is not a function 这种情况怎么处理

### ISSUE THREAD

**Issue by CasonCaly** [Tencent/puerts#258]
Puerts的版本是昨天的版本
以下是C++的父类代码，继承UObject
```
#pragma once

#include "CoreMinimal.h"

#include "Abilities/GameplayAbilityTypes.h"
#include "UObject/Object.h"
#include "RexTargetType.generated.h"

class ARexCharacter;

UCLASS(Blueprintable, meta = (ShowWorldContextPin))
class GASRPG_API URexTargetType : public UObject
{
	GENERATED_BODY()

public:
	URexTargetType(){};
	UFUNCTION(BlueprintNativeEvent)
	void GetTargets(ARexCharacter* TargetingCharacter,  AActor* TargetingActor, FGameplayEventData EventData, TArray<FHitResult>& OutHitResults, TArray<AActor*>& OutActors) const;
};
```
TS这边继承这个C++类
```
import * as UE from 'ue'
import { $ref, $unref, $set } from 'puerts';
class TargetType_SphereTrace extends UE.RexTargetType {
    
    OffsetFromActor:UE.Vector;
    SphereRadius:number;
    TraceLength:number;
    ObjectTypes:UE.TArray< UE.EObjectTypeQuery>;  
    DrawDebug:UE.EDrawDebugTrace; 

    Constructor(){
          
    }

    GetTargets(TargetingCharacter: UE.RexCharacter, TargetingActor: UE.Actor, EventData: UE.GameplayEventData, OutHitResults: UE.$Ref<UE.TArray<UE.HitResult>>, OutActors: UE.$Ref<UE.TArray<UE.Actor>>): void{

    }
}
export default TargetType_SphereTrace;
```
然后就报标题中的错误了
```
Puerts: Error: (0x0000017D82783510) TypeError: UE[type.symbol.getName(...)].StaticClass is not a function
    at getUClassOfType (F:\unreal\udemo\GasRPG\Content\JavaScript\PuertsEditor\CodeAnalyze.js:1146:54)
    at tsTypeToPinType (F:\unreal\udemo\GasRPG\Content\JavaScript\PuertsEditor\CodeAnalyze.js:1204:42)
    at tsTypeToPinType (F:\unreal\udemo\GasRPG\Content\JavaScript\PuertsEditor\CodeAnalyze.js:1220:42)
    at F:\unreal\udemo\GasRPG\Content\JavaScript\PuertsEditor\CodeAnalyze.js:1376:43
    at Array.forEach (<anonymous>)
    at onBlueprintTypeAddOrChange (F:\unreal\udemo\GasRPG\Content\JavaScript\PuertsEditor\CodeAnalyze.js:1327:22)
    at onSourceFileAddOrChange (F:\unreal\udemo\GasRPG\Content\JavaScript\PuertsEditor\CodeAnalyze.js:1129:29)
    at F:\unreal\udemo\GasRPG\Content\JavaScript\PuertsEditor\CodeAnalyze.js:1041:29
Puerts: Warning: (0x0000017D82783510) can not find pin type of typeArguments[0] TArray
Puerts: Warning: (0x0000017D82783510) ObjectTypes of TargetType_SphereTrace not support!
```

**Comment by CasonCaly** [comment]
上面用到了GameAbilitySystem插件

**Comment by chexiongsheng** [comment]
这是启动时报的吧？你试试进入编辑器后，然后修改下你这个TS类，看看报错不？

**Comment by chexiongsheng** [comment]
我猜是puerts模块启动得早，GameAbilitySystem还没启动 导致的。
所以让你编辑器后，然后修改下你这个TS类，看看是否报错来确认这猜想。

**Comment by CasonCaly** [comment]
```
import * as UE from 'ue'
import { $ref, $unref, $set } from 'puerts';
class TargetType_SphereTrace extends UE.RexTargetType {
    
    OffsetFromActor:UE.Vector;
    SphereRadius:number;
    TraceLength:number;
    ObjectTypes:UE.TArray< UE.Actor>;  
    //ObjectTypes:UE.TArray< UE.EObjectTypeQuery>;  
    //DrawDebug:UE.EDrawDebugTrace; 

    Constructor(){
          
    }

    GetTargets(TargetingCharacter: UE.RexCharacter, TargetingActor: UE.Actor, EventData: UE.GameplayEventData, OutHitResults: UE.$Ref<UE.TArray<UE.HitResult>>, OutActors: UE.$Ref<UE.TArray<UE.Actor>>): void{

    }
}
export default TargetType_SphereTrace;
```

成员变量只要和枚举有关系就不行

**Comment by chexiongsheng** [comment]
最新版本支持枚举了
