### ISSUE TITLE
 (unreal)当UExtensionMethods在其他插件的时候，会出现延迟加载的情况

### ISSUE THREAD

**Issue by CasonCaly** [Tencent/puerts#264]
我扩展了一个UWorld的函数
`class PUERTS_API UWorldExtensionMethods : public UExtensionMethods
{
    GENERATED_BODY()

    UFUNCTION(BlueprintCallable, Category = "WorldExtension")
    static AActor *SpawnActor(UWorld *World, UClass* Class, const FTransform &Transform, ESpawnActorCollisionHandlingMethod SpawnCollisionHandlingOverride, AActor *Owner, APawn *Instigator);

};`
这个位于Puerts这个插件中
![image](https://user-images.githubusercontent.com/5086299/119594248-02291b00-be0e-11eb-9e8b-d691f7eb922d.png)
这个时候我调用SpawnActor函数是可以正常的。
当我这份代码移到我自己的插件中的时候，就会出现延迟加载的情况
![image](https://user-images.githubusercontent.com/5086299/119594715-e2debd80-be0e-11eb-8dd6-884c98bee30f.png)

`Puerts: Error: (0x00000186E46BF450) call MainController_C::ReceiveBeginPlay of 000001873E414100 fail: F:\unreal\udemo\GasRPG\Content\JavaScript\Player\MainCharacter.js:162: TypeError: World.SpawnActor is not a function
TypeError: World.SpawnActor is not a function
    at Object.CreateAllWeapons (F:\unreal\udemo\GasRPG\Content\JavaScript\Player\MainCharacter.js:162:37)
    at Object.ReceiveBeginPlay (F:\unreal\udemo\GasRPG\Content\JavaScript\Player\MainController.js:19:30)`
World.SpawnActor这个函数就找不到了。
当然，在编译的时候有这两个警告
`  Warning: Plugin 'RexCore' does not list plugin 'Puerts' as a dependency, but module 'RexCore' depends on 'JsEnv'.`
`  Warning: Plugin 'RexCore' does not list plugin 'Puerts' as a dependency, but module 'RexCore' depends on 'Puerts'.`
但我该加的module都加了
![image](https://user-images.githubusercontent.com/5086299/119595231-cf802200-be0f-11eb-8e63-6692ac0be21f.png)

**Comment by CasonCaly** [comment]
对了，只是在第一次运行的时候会提示找不到，后面的就没问题

**Comment by CasonCaly** [comment]
`void FRexCoreModule::StartupModule()
{
	IPuertsModule::Get().InitExtensionMethodsMap();
}
`
我再自己的插件入口这么调用就可以了
