### ISSUE TITLE
When packaging android，ts binding failure

### ISSUE THREAD

**Issue by ljporljp** [Tencent/puerts#510]

**Comment by chexiongsheng** [comment]
Add Context/JavaScript to "Additional Not-Asset Directories to Package"

**Comment by chexiongsheng** [comment]
Any error？

**Comment by ljporljp** [comment]
Black screen, but no error.

**Comment by ljporljp** [comment]
Looks like packaging pc is the same.

**Comment by cchorseless** [comment]
> any error in log?

kaging (Android (ASTC)):   Directory ../Plugins/Online/Android/OnlineSubsystemGooglePlay/Source/Java/BillingApiV2 copied to E:/project/unreal_project/ts_frame/Intermediate/Android/armv7/src
UATHelper: Packaging (Android (ASTC)):   Copying permission_library directory to staging before build
UATHelper: Packaging (Android (ASTC)):   
UATHelper: Packaging (Android (ASTC)):   Directory ..//Source/ThirdParty/AndroidPermission/permission_library copied to E:/project/unreal_project/ts_frame/Intermediate/Android/armv7/JavaLibs/permission_library
UATHelper: Packaging (Android (ASTC)):   
UATHelper: Packaging (Android (ASTC)):   ==== Writing to OBB data file E:\project\unreal_project\ts_frame\Intermediate\Android\armv7\src\com\yuezhidi\demo\OBBData.java ====
UATHelper: Packaging (Android (ASTC)):   
UATHelper: Packaging (Android (ASTC)):   ==== OBB data file up to date so not writing. ====
UATHelper: Packaging (Android (ASTC)):   Copying libplaycore.so and proguard files
UATHelper: Packaging (Android (ASTC)):   
UATHelper: Packaging (Android (ASTC)):   File D:/unreal/UE_4.26/Engine/Plugins/Runtime/GooglePAD/Source/GooglePAD/../ThirdParty/play-core-native-sdk/libs/armeabi-v7a/ndk21.4.7075529/c++_shared/libplaycore.so copied to E:/project/unreal_project/ts_frame/Intermediate/Android/armv7/libs/armeabi-v7a/libplaycore.so
UATHelper: Packaging (Android (ASTC)):   Copying libvrapi.so
UATHelper: Packaging (Android (ASTC)):   
UATHelper: Packaging (Android (ASTC)):   File ..//Source/ThirdParty/Oculus/OVRPlugin/OVRPlugin/ExtLibs/armeabi-v7a/libvrapi.so copied to E:/project/unreal_project/ts_frame/Intermediate/Android/armv7/libs/armeabi-v7a/libvrapi.so
UATHelper: Packaging (Android (ASTC)):   Copying libOVRPlugin.so
UATHelper: Packaging (Android (ASTC)):   
UATHelper: Packaging (Android (ASTC)):   File ..//Source/ThirdParty/Oculus/OVRPlugin/OVRPlugin/Lib/armeabi-v7a/libOVRPlugin.so copied to E:/project/unreal_project/ts_frame/Intermediate/Android/armv7/libs/armeabi-v7a/libOVRPlugin.so
UATHelper: Packaging (Android (ASTC)):   
UATHelper: Packaging (Android (ASTC)):   File ..//Source/ThirdParty/Oculus/OVRPlugin/OVRPlugin/ExtLibs/VrApi.jar does not exist, not copied!
UATHelper: Packaging (Android (ASTC)):   
UATHelper: Packaging (Android (ASTC)):   File ..//Source/ThirdParty/Oculus/OVRPlugin/OVRPlugin/ExtLibs/SystemUtils.jar does not exist, not copied!
UATHelper: Packaging (Android (ASTC)):   
UATHelper: Packaging (Android (ASTC)):   ====2021/11/10 22:56:41====PERFORMING FINAL APK PACKAGE OPERATION=====-armv7===========================================
UATHelper: Packaging (Android (ASTC)):   Fixing minSdkVersion; NDK level above 19 requires minSdkVersion of 21 (arch=armv7)
UATHelper: Packaging (Android (ASTC)):   
UATHelper: Packaging (Android (ASTC)):   Creating rungradle.bat to work around commandline length limit (using unused drive letter Z:)
UATHelper: Packaging (Android (ASTC)):   Making .apk with Gradle...
UATHelper: Packaging (Android (ASTC)):   To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/6.1.1/userguide/gradle_daemon.html.
UATHelper: Packaging (Android (ASTC)):   Daemon will be stopped at the end of the build stopping after processing
UATHelper: Packaging (Android (ASTC)):   java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7
UATHelper: Packaging (Android (ASTC)):     at org.codehaus.groovy.vmplugin.VMPluginFactory.<clinit>(VMPluginFactory.java:43)
UATHelper: Packaging (Android (ASTC)):     at org.codehaus.groovy.reflection.GroovyClassValueFactory.<clinit>(GroovyClassValueFactory.java:35)
UATHelper: Packaging (Android (ASTC)):     at org.codehaus.groovy.reflection.ClassInfo.<clinit>(ClassInfo.java:107)
UATHelper: Packaging (Android (ASTC)):     at org.codehaus.groovy.reflection.ReflectionCache.getCachedClass(ReflectionCache.java:95)
UATHelper: Packaging (Android (ASTC)):     at org.codehaus.groovy.reflection.ReflectionCache.<clinit>(ReflectionCache.java:39)
UATHelper: Packaging (Android (ASTC)):     at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.registerMethods(MetaClassRegistryImpl.java:210)
UATHelper: Packaging (Android (ASTC)):     at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:108)
UATHelper: Packaging (Android (ASTC)):     at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:86)
UATHelper: Packaging (Android (ASTC)):     at groovy.lang.GroovySystem.<clinit>(GroovySystem.java:36)
UATHelper: Packaging (Android (ASTC)):     at org.codehaus.groovy.runtime.InvokerHelper.<clinit>(InvokerHelper.java:86)
UATHelper: Packaging (Android (ASTC)):     at groovy.lang.GroovyObjectSupport.getDefaultMetaClass(GroovyObjectSupport.java:59)
UATHelper: Packaging (Android (ASTC)):     at groovy.lang.GroovyObjectSupport.<init>(GroovyObjectSupport.java:32)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.internal.extensibility.DefaultExtraPropertiesExtension.<init>(DefaultExtraPropertiesExtension.java:29)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.internal.extensibility.DefaultConvention.<init>(DefaultConvention.java:49)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.internal.extensibility.ExtensibleDynamicObject.<init>(ExtensibleDynamicObject.java:60)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.internal.instantiation.generator.MixInExtensibleDynamicObject.<init>(MixInExtensibleDynamicObject.java:35)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.initialization.DefaultSettings_Decorated.getAsDynamicObject(Unknown Source)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.initialization.SettingsFactory.createSettings(SettingsFactory.java:58)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.initialization.ScriptEvaluatingSettingsProcessor.process(ScriptEvaluatingSettingsProcessor.java:61)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.initialization.PropertiesLoadingSettingsProcessor.process(PropertiesLoadingSettingsProcessor.java:38)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.initialization.SettingsEvaluatedCallbackFiringSettingsProcessor.process(SettingsEvaluatedCallbackFiringSettingsProcessor.java:34)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.initialization.RootBuildCacheControllerSettingsProcessor.process(RootBuildCacheControllerSettingsProcessor.java:36)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.initialization.BuildOperationSettingsProcessor$2.call(BuildOperationSettingsProcessor.java:50)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.initialization.BuildOperationSettingsProcessor$2.call(BuildOperationSettingsProcessor.java:47)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.initialization.BuildOperationSettingsProcessor.process(BuildOperationSettingsProcessor.java:47)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.initialization.DefaultSettingsLoader.findSettingsAndLoadIfAppropriate(DefaultSettingsLoader.java:102)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.initialization.DefaultSettingsLoader.findAndLoadSettings(DefaultSettingsLoader.java:45)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.initialization.SettingsAttachingSettingsLoader.findAndLoadSettings(SettingsAttachingSettingsLoader.java:35)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.internal.composite.CommandLineIncludedBuildSettingsLoader.findAndLoadSettings(CommandLineIncludedBuildSettingsLoader.java:34)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.internal.composite.ChildBuildRegisteringSettingsLoader.findAndLoadSettings(ChildBuildRegisteringSettingsLoader.java:52)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.internal.composite.CompositeBuildSettingsLoader.findAndLoadSettings(CompositeBuildSettingsLoader.java:35)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.initialization.DefaultSettingsPreparer.prepareSettings(DefaultSettingsPreparer.java:36)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.initialization.BuildOperatingFiringSettingsPreparer$LoadBuild.doLoadBuild(BuildOperatingFiringSettingsPreparer.java:59)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.initialization.BuildOperatingFiringSettingsPreparer$LoadBuild.run(BuildOperatingFiringSettingsPreparer.java:54)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.initialization.BuildOperatingFiringSettingsPreparer.prepareSettings(BuildOperatingFiringSettingsPreparer.java:42)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.initialization.DefaultGradleLauncher.prepareSettings(DefaultGradleLauncher.java:197)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.initialization.DefaultGradleLauncher.doClassicBuildStages(DefaultGradleLauncher.java:141)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:130)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.initialization.DefaultGradleLauncher.executeTasks(DefaultGradleLauncher.java:110)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.internal.invocation.GradleBuildController$1.execute(GradleBuildController.java:60)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.internal.invocation.GradleBuildController$1.execute(GradleBuildController.java:57)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.internal.invocation.GradleBuildController$3.create(GradleBuildController.java:85)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.internal.invocation.GradleBuildController$3.create(GradleBuildController.java:78)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:189)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.internal.work.StopShieldingWorkerLeaseService.withLocks(StopShieldingWorkerLeaseService.java:40)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.internal.invocation.GradleBuildController.doBuild(GradleBuildController.java:78)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.internal.invocation.GradleBuildController.run(GradleBuildController.java:57)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:31)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.launcher.exec.BuildOutcomeReportingBuildActionRunner.run(BuildOutcomeReportingBuildActionRunner.java:63)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.tooling.internal.provider.ValidatingBuildActionRunner.run(ValidatingBuildActionRunner.java:32)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.launcher.exec.BuildCompletionNotifyingBuildActionRunner.run(BuildCompletionNotifyingBuildActionRunner.java:39)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.call(RunAsBuildOperationBuildActionRunner.java:51)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.call(RunAsBuildOperationBuildActionRunner.java:45)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:45)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:50)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:47)
PackagingResults: Error: Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7
UATHelper: Packaging (Android (ASTC)):     at org.gradle.composite.internal.DefaultRootBuildState.run(DefaultRootBuildState.java:80)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:47)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:31)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:42)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:28)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:78)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:52)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.tooling.internal.provider.SubscribableBuildActionExecuter.execute(SubscribableBuildActionExecuter.java:60)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.tooling.internal.provider.SubscribableBuildActionExecuter.execute(SubscribableBuildActionExecuter.java:38)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.tooling.internal.provider.SessionScopeBuildActionExecuter.execute(SessionScopeBuildActionExecuter.java:68)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.tooling.internal.provider.SessionScopeBuildActionExecuter.execute(SessionScopeBuildActionExecuter.java:38)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:37)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:26)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:43)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:29)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:60)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:32)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:55)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:41)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:48)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:32)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:68)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:39)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:27)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:35)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:78)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:75)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.util.Swapper.swap(Swapper.java:38)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:75)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:50)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:63)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:82)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:52)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
UATHelper: Packaging (Android (ASTC)):     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
UATHelper: Packaging (Android (ASTC)):     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
UATHelper: Packaging (Android (ASTC)):     at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
UATHelper: Packaging (Android (ASTC)):     at java.base/java.lang.Thread.run(Thread.java:833)
UATHelper: Packaging (Android (ASTC)):   
UATHelper: Packaging (Android (ASTC)):   FAILURE: Build failed with an exception.
UATHelper: Packaging (Android (ASTC)):   
UATHelper: Packaging (Android (ASTC)):   * What went wrong:
UATHelper: Packaging (Android (ASTC)):   Could not initialize class org.codehaus.groovy.reflection.ReflectionCache
UATHelper: Packaging (Android (ASTC)):   
UATHelper: Packaging (Android (ASTC)):   * Try:
UATHelper: Packaging (Android (ASTC)):   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
UATHelper: Packaging (Android (ASTC)):   
UATHelper: Packaging (Android (ASTC)):   * Get more help at https://help.gradle.org
UATHelper: Packaging (Android (ASTC)):   
UATHelper: Packaging (Android (ASTC)):   BUILD FAILED in 5s
UATHelper: Packaging (Android (ASTC)):   ERROR: cmd.exe failed with args /c "E:\project\unreal_project\ts_frame\Intermediate\Android\armv7\gradle\rungradle.bat" :app:assembleDebug
PackagingResults: Error: cmd.exe failed with args /c "E:\project\unreal_project\ts_frame\Intermediate\Android\armv7\gradle\rungradle.bat" :app:assembleDebug
UATHelper: Packaging (Android (ASTC)): Took 9.0458585s to run UnrealBuildTool.exe, ExitCode=6
UATHelper: Packaging (Android (ASTC)): UnrealBuildTool failed. See log for more details. (C:\Users\74180\AppData\Roaming\Unreal Engine\AutomationTool\Logs\D+unreal+UE_4.26\UBT-frame-Android-Development.txt)
UATHelper: Packaging (Android (ASTC)): AutomationTool exiting with ExitCode=6 (6)
UATHelper: Packaging (Android (ASTC)): BUILD FAILED
PackagingResults: Error: Unknown Error

**Comment by VegetableWithChicken** [comment]
version of unreal is ?
