### ISSUE TITLE
[Unity]将C#的字典作为参数在ts运行时报错

### ISSUE THREAD

**Issue by 3354** [Tencent/puerts#543]
## detail | 详细描述
我想将ts中的字典数据传递到C#层，并做了如下处理：
let List = $generic(System.Collections.Generic.List$1, System.Int32)
            let Dictionary  = $generic(System.Collections.Generic.Dictionary$2,System.String, List)
            let dic = new Dictionary<number,number>()
            for (const configElement of config.keys()) {
                dic.Add(configElement,config.get(configElement))
            }
GameTool.GetInstance().Test(dic)
Test方法定义:
public void Test(Dictionary<int, int> dic)
	{
		Debug.Log("收到字典:" + dic.Count);
	}

运行之后报了如下错误:
Exception: Assets\DW\_Resources\JS\JS\Module\Core\Manager\ShopPayManager.js:25: Error: c# exception:Assets\DW\_Resources\JS\JS\Module\Core\Manager\ShopPayManager.js:48: Error: c# exception:Object reference not set to an instance of an object,stack:  at GameTool.Test (System.Collections.Generic.Dictionary`2[TKey,TValue] dic) [0x00001] in H:\Work\UniversalGift\Assets\DW\Scripts\Core\GameTool.cs:285 
  at PuertsStaticWrap.GameTool_Wrap.M_Test (System.IntPtr isolate, System.IntPtr info, System.IntPtr self, System.Int32 paramLen, System.Int64 data) [0x00029] in H:\Work\UniversalGift\Assets\DW\Gen\GameTool_Wrap.cs:421 
            csharp_1.GameTool.GetInstance().Test(dic);
                                            ^
Error: c# exception:Object reference not set to an instance of an object,stack:  at GameTool.Test (System.Collections.Generic.Dictionary`2[TKey,TValue] dic) [0x00001] in H:\Work\UniversalGift\Assets\DW\Scripts\Core\GameTool.cs:285 
  at PuertsStaticWrap.GameTool_Wrap.M_Test (System.IntPtr isolate, System.IntPtr info, System.IntPtr self, System.Int32 paramLen, System.Int64 data) [0x00029] in H:\Work\UniversalGift\Assets\DW\Gen\GameTool_Wrap.cs:421 
    at ShopPayManager.OnPaySuccess (Assets\DW\_Resources\JS\JS\Module\Core\Manager\ShopPayManager.js:48:45)
    at Assets\DW\_Resources\JS\JS\Module\Core\Event\Handler.js:19:21
    at ShopPayManager.BuyGift (Assets\DW\_Resources\JS\JS\Module\Core\Manager\ShopPayManager.js:25:45)
    at ShopUI.OnBuyItemBig (Assets\DW\_Resources\JS\JS\Module\Core\UIPanel\ShopUI.js:134:55)
    at Assets\DW\_Resources\JS\JS\Module\Core\Event\Handler.js:19:21,stack:  at Puerts.GenericDelegate.Action[T1,T2,T3] (T1 p1, T2 p2, T3 p3) [0x000ae] in H:\Work\UniversalGift\Assets\DW\Scripts\ThirdParty\Puerts\Src\GenericDelegate.cs:365 
  at Wb.PayManager.PayCheckCallBack (System.String param) [0x00082] in H:\Work\UniversalGift\Assets\Wb\Scripts\Pay\PayManager.cs:93 
  at Wb.PayPc.OrderPay (System.Int32 payId) [0x00012] in H:\Work\UniversalGift\Assets\Wb\Scripts\Pay\platform\PayPc.cs:17 
  at Wb.PayManager.OrderPay (System.Int32 payId, System.Action`3[T1,T2,T3] callFun) [0x00008] in H:\Work\UniversalGift\Assets\Wb\Scripts\Pay\PayManager.cs:37 
  at DW.Scripts.Core.SDKManager.BuyProduct (System.Int32 id, System.Action`3[T1,T2,T3] callBack) [0x00001] in H:\Work\UniversalGift\Assets\DW\Scripts\Core\SDKManager.cs:108 
  at PuertsStaticWrap.DW_Scripts_Core_SDKManager_Wrap.F_BuyProduct (System.IntPtr isolate, System.IntPtr info, System.IntPtr self, System.Int32 paramLen, System.Int64 data) [0x00030] in H:\Work\UniversalGift\Assets\DW\Gen\DW_Scripts_Core_SDKManager_Wrap.cs:431 
        csharp_1.DW.Scripts.Core.SDKManager.BuyProduct(payId, Handler_1.Handler.Create(this, this.OnPaySuccess));
                                            ^
Error: c# exception:Assets\DW\_Resources\JS\JS\Module\Core\Manager\ShopPayManager.js:48: Error: c# exception:Object reference not set to an instance of an object,stack:  at GameTool.Test (System.Collections.Generic.Dictionary`2[TKey,TValue] dic) [0x00001] in H:\Work\UniversalGift\Assets\DW\Scripts\Core\GameTool.cs:285 
  at PuertsStaticWrap.GameTool_Wrap.M_Test (System.IntPtr isolate, System.IntPtr info, System.IntPtr self, System.Int32 paramLen, System.Int64 data) [0x00029] in H:\Work\UniversalGift\Assets\DW\Gen\GameTool_Wrap.cs:421 
            csharp_1.GameTool.GetInstance().Test(dic);
                                            ^
Error: c# exception:Object reference not set to an instance of an object,stack:  at GameTool.Test (System.Collections.Generic.Dictionary`2[TKey,TValue] dic) [0x00001] in H:\Work\UniversalGift\Assets\DW\Scripts\Core\GameTool.cs:285 
  at PuertsStaticWrap.GameTool_Wrap.M_Test (System.IntPtr isolate, System.IntPtr info, System.IntPtr self, System.Int32 paramLen, System.Int64 data) [0x00029] in H:\Work\UniversalGift\Assets\DW\Gen\GameTool_Wrap.cs:421 
    at ShopPayManager.OnPaySuccess (Assets\DW\_Resources\JS\JS\Module\Core\Manager\ShopPayManager.js:48:45)
    at Assets\DW\_Resources\JS\JS\Module\Core\Event\Handler.js:19:21
    at ShopPayManager.BuyGift (Assets\DW\_Resources\JS\JS\Module\Core\Manager\ShopPayManager.js:25:45)
    at ShopUI.OnBuyItemBig (Assets\DW\_Resources\JS\JS\Module\Core\UIPanel\ShopUI.js:134:55)
    at Assets\DW\_Resources\JS\JS\Module\Core\Event\Handler.js:19:21,stack:  at Puerts.GenericDelegate.Action[T1,T2,T3] (T1 p1, T2 p2, T3 p3) [0x000ae] in H:\Work\UniversalGift\Assets\DW\Scripts\ThirdParty\Puerts\Src\GenericDelegate.cs:365 
  at Wb.PayManager.PayCheckCallBack (System.String param) [0x00082] in H:\Work\UniversalGift\Assets\Wb\Scripts\Pay\PayManager.cs:93 
  at Wb.PayPc.OrderPay (System.Int32 payId) [0x00012] in H:\Work\UniversalGift\Assets\Wb\Scripts\Pay\platform\PayPc.cs:17 
  at Wb.PayManager.OrderPay (System.Int32 payId, System.Action`3[T1,T2,T3] callFun) [0x00008] in H:\Work\UniversalGift\Assets\Wb\Scripts\Pay\PayManager.cs:37 
  at DW.Scripts.Core.SDKManager.BuyProduct (System.Int32 id, System.Action`3[T1,T2,T3] callBack) [0x00001] in H:\Work\UniversalGift\Assets\DW\Scripts\Core\SDKManager.cs:108 
  at PuertsStaticWrap.DW_Scripts_Core_SDKManager_Wrap.F_BuyProduct (System.IntPtr isolate, System.IntPtr info, System.IntPtr self, System.Int32 paramLen, System.Int64 data) [0x00030] in H:\Work\UniversalGift\Assets\DW\Gen\DW_Scripts_Core_SDKManager_Wrap.cs:431 
    at ShopPayManager.BuyGift (Assets\DW\_Resources\JS\JS\Module\Core\Manager\ShopPayManager.js:25:45)
    at ShopUI.OnBuyItemBig (Assets\DW\_Resources\JS\JS\Module\Core\UIPanel\ShopUI.js:134:55)
    at Assets\DW\_Resources\JS\JS\Module\Core\Event\Handler.js:19:21
Puerts.GenericDelegate.Action[T1] (T1 p1) (at Assets/DW/Scripts/ThirdParty/Puerts/Src/GenericDelegate.cs:326)
FairyGUI.EventBridge.CallInternal (FairyGUI.EventContext context) (at Assets/DW/Scripts/ThirdParty/FairyGUI/Scripts/Event/EventBridge.cs:149)
FairyGUI.EventDispatcher.BubbleEvent (System.String strType, System.Object data, System.Collections.Generic.List`1[T] addChain) (at Assets/DW/Scripts/ThirdParty/FairyGUI/Scripts/Event/EventDispatcher.cs:317)
FairyGUI.EventDispatcher.BubbleEvent (System.String strType, System.Object data) (at Assets/DW/Scripts/ThirdParty/FairyGUI/Scripts/Event/EventDispatcher.cs:360)
FairyGUI.Stage.HandleMouseEvents () (at Assets/DW/Scripts/ThirdParty/FairyGUI/Scripts/Core/Stage.cs:1227)
FairyGUI.Stage.HandleEvents () (at Assets/DW/Scripts/ThirdParty/FairyGUI/Scripts/Core/Stage.cs:1069)
FairyGUI.Stage.InternalUpdate () (at Assets/DW/Scripts/ThirdParty/FairyGUI/Scripts/Core/Stage.cs:873)
FairyGUI.StageEngine.LateUpdate () (at Assets/DW/Scripts/ThirdParty/FairyGUI/Scripts/Core/StageEngine.cs:22)

**Comment by Joycraft** [comment]
为什么你定义的是`Dictionary< string, List< int>>`调用的时候却是`Dictionary< int,int>`

**Comment by 3354** [comment]
> 为什么你定义的是`Dictionary< string, List< int>>`调用的时候却是`Dictionary< int,int>`
非常感谢，确实是这样，我把类型弄错了，问题已解决

**Comment by 3354** [comment]
> 为什么你定义的是`Dictionary< string, List< int>>`调用的时候却是`Dictionary< int,int>`
非常感谢，确实是这样，我把类型弄错了，问题已解决
