### ISSUE TITLE
[Unreal]TypeError: this.GunLocation.SetupAttachment is not a function

### ISSUE THREAD

**Issue by dawnarc** [Tencent/puerts#560]
不知道是bug还是我使用不对

## error log | 日志或报错信息
```
Puerts: Error: (0x00000211B09E8810) js callback exception D:\workspace\ue4_game\PuertsIssue\Content\JavaScript\TS_Player.js:19: TypeError: this.GunLocation.SetupAttachment is not a function
TypeError: this.GunLocation.SetupAttachment is not a function
    at Object.Constructor (D:\workspace\ue4_game\PuertsIssue\Content\JavaScript\TS_Player.js:19:26)
Puerts: Error: (0x00000211B09E8810) js callback exception D:\workspace\ue4_game\PuertsIssue\Content\JavaScript\TS_Rifle.js:11: TypeError: Cannot create property 'StaticMesh' on number '0'
TypeError: Cannot create property 'StaticMesh' on number '0'
    at Object.Constructor (D:\workspace\ue4_game\PuertsIssue\Content\JavaScript\TS_Rifle.js:11:33)
    at Object.ReceiveBeginPlay (D:\workspace\ue4_game\PuertsIssue\Content\JavaScript\TS_Player.js:37:47)
LogActor: Warning: TS_Rifle_C /Game/BlockBreaker/Maps/UEDPIE_0_TutorialMap.TutorialMap:PersistentLevel.TS_Rifle_C_0 has natively added scene component(s), but none of them were set as the actor's RootComponent - picking one arbitrarily
Puerts: Error: (0x00000211B09E8810) call TS_Player_C::ReceiveBeginPlay of 00000211C21B1D00 fail: D:\workspace\ue4_game\PuertsIssue\Content\JavaScript\TS_Player.js:39: TypeError: this.EquippedGun.K2_AttachToComponent is not a function
TypeError: this.EquippedGun.K2_AttachToComponent is not a function
    at Object.ReceiveBeginPlay (D:\workspace\ue4_game\PuertsIssue\Content\JavaScript\TS_Player.js:39:26)
```

## context | 编译/运行环境

Windows 10 x64
UE4.27.0
Visual Studio 2019
Nodejs v16.13.0 x64
PuerTS master分支
TypeScript编辑器为 Nodepad++

## how to reproduce | 复现步骤
1. 用UE4Editor新建一个空白的UE4 C++工程（非纯蓝图工程）。

2. 按照官方文档（[跟我用TypeScript做一个FPS游戏](https://zhuanlan.zhihu.com/p/346531865)）将模型资产加入空工程，并将puerts插件加入空工程，并执行`node enable_puerts_module.js`

3. 不按照文档一步一步写TypeScript逻辑代码，而是将先前写好的代码一次性拷贝到`[工程]/TypeScript/`目录下。
  这里获取官方文档上的4个ts脚本：[puerts_fps_demo工程的TS脚本](https://github.com/chexiongsheng/puerts_fps_demo/tree/master/src/TypeScript)
  我的方式是在`[工程]/TypeScript/`下依次新建：`ObjectExt.ts`、`TS_BaseGun.ts`、`TS_Rifle.ts`、`TS_Player.ts`，并依次从官方代码中拷贝对应ts文件的所有内容粘贴进来并保存。
  
4. VS编译并启动UE4工程，然后点击UE4插件按钮`ue.d.ts`

5. 然后为每个ts文件添加空行，来触发热编译并生成对应的UE4蓝图资产：
    ![image](https://user-images.githubusercontent.com/3351764/143773378-bc6848c8-ad57-4da6-84d9-7439c222d9fc.png)
    
6. 然后新建一个`GameMode`蓝图，同时在World Settings中设置好`GameMode`和`Default Pawn Class`：
![image](https://user-images.githubusercontent.com/3351764/143773706-5113ab20-3722-454b-a918-b7c04bbdfdca.png)
![image](https://user-images.githubusercontent.com/3351764/143773713-9e447b30-b727-4097-82f6-25b87c7defee.png)

7. 运行游戏，会抛出错误：
```
Puerts: Error: (0x00000211A24E6930) js callback exception D:\workspace\ue4_game\PuertsIssue\Content\JavaScript\TS_Rifle.js:10: TypeError: this.CreateDefaultSubobjectGeneric is not a function
TypeError: this.CreateDefaultSubobjectGeneric is not a function
    at Object.Constructor (D:\workspace\ue4_game\PuertsIssue\Content\JavaScript\TS_Rifle.js:10:29)
Puerts: Display: (0x00000211A24E6930) Bind module [TS_BaseGun] 
Puerts: Display: (0x00000211A24E6930) Bind module [TS_Rifle] 
Puerts: Error: (0x00000211A24E6930) js callback exception D:\workspace\ue4_game\PuertsIssue\Content\JavaScript\TS_Rifle.js:10: TypeError: this.CreateDefaultSubobjectGeneric is not a function
TypeError: this.CreateDefaultSubobjectGeneric is not a function
    at Object.Constructor (D:\workspace\ue4_game\PuertsIssue\Content\JavaScript\TS_Rifle.js:10:29)
LogUObjectHash: Compacting FUObjectHashTables data took   0.84ms
```
这个错误好解决：在`TS_Rifle.js`再次添加空行或者注掉`this.CreateDefaultSubobjectGeneric`后保存在再打开在保存。

8. 步骤7的错误解决后，再次运行游戏，会报新的错误：
```
LogNativeClassHierarchy: Verbose: Native class hierarchy updated for 'MovieSceneCapture' in 0.0003 seconds. Added 20 classes and 0 folders.
Puerts: Error: (0x00000211B09E8810) js callback exception D:\workspace\ue4_game\PuertsIssue\Content\JavaScript\TS_Player.js:19: TypeError: this.GunLocation.SetupAttachment is not a function
TypeError: this.GunLocation.SetupAttachment is not a function
    at Object.Constructor (D:\workspace\ue4_game\PuertsIssue\Content\JavaScript\TS_Player.js:19:26)
Puerts: Error: (0x00000211B09E8810) js callback exception D:\workspace\ue4_game\PuertsIssue\Content\JavaScript\TS_Rifle.js:11: TypeError: Cannot create property 'StaticMesh' on number '0'
TypeError: Cannot create property 'StaticMesh' on number '0'
    at Object.Constructor (D:\workspace\ue4_game\PuertsIssue\Content\JavaScript\TS_Rifle.js:11:33)
    at Object.ReceiveBeginPlay (D:\workspace\ue4_game\PuertsIssue\Content\JavaScript\TS_Player.js:37:47)
LogActor: Warning: TS_Rifle_C /Game/BlockBreaker/Maps/UEDPIE_0_TutorialMap.TutorialMap:PersistentLevel.TS_Rifle_C_0 has natively added scene component(s), but none of them were set as the actor's RootComponent - picking one arbitrarily
Puerts: Error: (0x00000211B09E8810) call TS_Player_C::ReceiveBeginPlay of 00000211C21B1D00 fail: D:\workspace\ue4_game\PuertsIssue\Content\JavaScript\TS_Player.js:39: TypeError: this.EquippedGun.K2_AttachToComponent is not a function
TypeError: this.EquippedGun.K2_AttachToComponent is not a function
    at Object.ReceiveBeginPlay (D:\workspace\ue4_game\PuertsIssue\Content\JavaScript\TS_Player.js:39:26)
PIE: Server logged in
```
此时这个错误怎么都无法解决，尝试过的方法包括：点击`ue.d.ts`按钮、注掉这些报错的代码保存再逐步打开、重启编辑器、重启机器。

**Comment by chexiongsheng** [comment]
新绑定方案的bug

**Comment by chexiongsheng** [comment]
更新一下

**Comment by chexiongsheng** [comment]
之前的问题会导致错误的蓝图生成。看下修复那里，修复前，Properties会有多余的条目。这关系到UStruct的初始化：
~~~c++
void FScriptStructWrapper::New(v8::Isolate* Isolate, v8::Local<v8::Context>& Context, const v8::FunctionCallbackInfo<v8::Value>& Info)
{
//...
                    Memory = Alloc(static_cast<UScriptStruct*>(Struct.Get()));
                    const int Count = Info.Length() < Properties.size() ? Info.Length() : Properties.size();
                    for (int i = 0; i < Count; ++i)
                    {
                        Properties[i]->JsToUEInContainer(Isolate, Context, Info[i], Memory, false);
                    }
// ...
    }
~~~
多余的Properties会把UStruct的字段置空。而生成蓝图，对于类型都是通过FPEGraphPinType传递（一个UStruct），这会导致所有的类型信息都是默认值，也就是int。

**Comment by dawnarc** [comment]
@chexiongsheng 感谢车神保姆级解答！受教非浅:+1: PuerTS yyds :punch:
