### ISSUE TITLE
[Unity] 生成代码下，$generic报错

### ISSUE THREAD

**Issue by bluedoom** [Tencent/puerts#564]
## error log | 日志或报错信息
Exception: puerts\csharp.js:121: Error: loadClass throw c# exception:Ambiguous match found.,stack:  at System.RuntimeType.GetMethodImpl (System.String name, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Reflection.CallingConventions callConv, System.Type[] types, System.Reflection.ParameterModifier[] modifiers) [0x00059] in <437ba245d8404784b9fbab9b439ac908>:0 
  at System.Type.GetMethod (System.String name, System.Reflection.BindingFlags bindingAttr) [0x0000e] in <437ba245d8404784b9fbab9b439ac908>:0 
  at Puerts.TypeRegister.RegisterType (System.IntPtr isolate, System.Type type, System.Boolean includeNoPublic) [0x00581] in D:\Projects\puerts_demo_official\Assets\Puerts\Src\TypeRegister.cs:621 
  at Puerts.TypeRegister.GetTypeId (System.IntPtr isolate, System.Type type, System.Boolean& isFirst) [0x00034] in D:\Projects\puerts_demo_official\Assets\Puerts\Src\TypeRegister.cs:744 
  at Puerts.TypeRegister.GetTypeId (System.IntPtr isolate, System.Type type) [0x00001] in D:\Projects\puerts_demo_official\Assets\Puerts\Src\TypeRegister.cs:759 
  at Puerts.JsEnv.LoadType (System.IntPtr isolate, System.IntPtr info, System.IntPtr self, System.Int32 paramLen) [0x0001a] in D:\Projects\puerts_demo_official\Assets\Puerts\Src\JsEnv.cs:414 

Error: loadClass throw c# exception:Ambiguous match found.,stack:  at System.RuntimeType.GetMethodImpl (System.String name, System.Reflection.BindingFlags bindingAttr, System.Reflection.Binder binder, System.Reflection.CallingConventions callConv, System.Type[] types, System.Reflection.ParameterModifier[] modifiers) [0x00059] in <437ba245d8404784b9fbab9b439ac908>:0 
  at System.Type.GetMethod (System.String name, System.Reflection.BindingFlags bindingAttr) [0x0000e] in <437ba245d8404784b9fbab9b439ac908>:0 
  at Puerts.TypeRegister.RegisterType (System.IntPtr isolate, System.Type type, System.Boolean includeNoPublic) [0x00581] in D:\Projects\puerts_demo_official\Assets\Puerts\Src\TypeRegister.cs:621 
  at Puerts.TypeRegister.GetTypeId (System.IntPtr isolate, System.Type type, System.Boolean& isFirst) [0x00034] in D:\Projects\puerts_demo_official\Assets\Puerts\Src\TypeRegister.cs:744 
  at Puerts.TypeRegister.GetTypeId (System.IntPtr isolate, System.Type type) [0x00001] in D:\Projects\puerts_demo_official\Assets\Puerts\Src\TypeRegister.cs:759 
  at Puerts.JsEnv.LoadType (System.IntPtr isolate, System.IntPtr info, System.IntPtr self, System.Int32 paramLen) [0x0001a] in D:\Projects\puerts_demo_official\Assets\Puerts\Src\JsEnv.cs:414 
    at makeGeneric (puerts\csharp.js:121:35)
    at QuickStart.js:51:40
    at executeModule (puerts\modular.js:50:9)
    at require (puerts\modular.js:99:17)
    at chunk:1:1
## context | 编译/运行环境
2019.4.31f1  
https://github.com/chexiongsheng/puerts_unity_demo
## how to reproduce | 复现步骤
1.生成代码
2.启动"Assets\Examples\05_Typescript\TsQuickStart.unity"

**Comment by zombieyang** [comment]
之前已经发现了，最近会改好
