### ISSUE TITLE
【Unity】 生成 index.d.ts 报错

### ISSUE THREAD

**Issue by Geequlim** [Tencent/puerts#597]
同步到最新的 puerts 代码后生成 index.d.ts 代码报错

## error log | 日志或报错信息
```
Exception: D:/work/repositories/unity-starter-kit/Assets\Puerts/Src/Editor/Resources\puerts/templates/type.tpl.cjs:1: SyntaxError: Unexpected token '?'

SyntaxError: Unexpected token '?'
    at executeModule (D:/work/repositories/unity-starter-kit/Assets\Puerts/Src/Editor/Resources\puerts/modular.js:44:30)
    at require (D:/work/repositories/unity-starter-kit/Assets\Puerts/Src/Editor/Resources\puerts/modular.js:99:17)
    at chunk:1:1
Puerts.JsEnv.Eval[TResult] (System.String chunk, System.String chunkName) (at Assets/csharp/Libraries/Puerts/Src/JsEnv.cs:227)
Puerts.Editor.Generator.Menu.GenerateCode (System.String saveTo, System.Boolean tsOnly) (at Assets/csharp/Libraries/Puerts/Src/Editor/Generator.cs:1504)
Puerts.Editor.Generator.Menu.GenerateDTS () (at Assets/csharp/Libraries/Puerts/Src/Editor/Generator.cs:1456)
```
## how to reproduce | 复现步骤
1. 同步到最新的 puerts 后出现
2. 撤回到 82f223ddcd39bbdd7634a00880dd0b5da78c7f01 没有此问题

**Comment by zombieyang** [comment]
有一个resources修改了文件名，但覆盖安装的情况下，Unity的Resource.Load会加载到旧文件。
