### ISSUE TITLE
[Unreal]安装reflect-metadata模块后无法正常运行

### ISSUE THREAD

**Issue by YoungForLong** [Tencent/puerts#640]
## error log | 日志或报错信息
[2022.01.17-06.33.46:511][665]Puerts: Display: (0x0000082A9D5FD790) Bind module [.../Component/AAComponent]

[2022.01.17-06.33.46:537][665]LogUObjectGlobals: Warning: Failed to find object 'Class None.TArray'

[2022.01.17-06.33.46:538][665]LogUObjectGlobals: Warning: Failed to find object 'ScriptStruct None.TArray'

[2022.01.17-06.33.46:538][665]LogUObjectGlobals: Warning: Failed to find object 'Enum None.TArray'

[2022.01.17-06.33.46:543][665]Puerts: Error: (0x0000082A9D5FD790) load module [.../AAComponent] exception F:\NZPrj\Nezha\Content\JavaScript\puerts\uelazyload.js:23: Error: can not find type:TArray

Error: can not find type:TArray

    at Object.get (F:\...\Content\JavaScript\puerts\uelazyload.js:23:38)

    at F:\...\BBComponent.js:738:34

    at executeModule (F:\...\Content\JavaScript\puerts\modular.js:68:9)

    at require (F:\...\Content\JavaScript\puerts\modular.js:125:17)

    at F:\...\Content\JavaScript\...\CCCharacter.js:20:30

    at executeModule (F:\...\Content\JavaScript\puerts\modular.js:68:9)

    at require (F:\...\Content\JavaScript\puerts\modular.js:125:17)

    at F:\...\Content\JavaScript\...\DDUtils.js:5:23

    at executeModule (F:\...\Content\JavaScript\puerts\modular.js:68:9)

    at require (F:\...\Content\JavaScript\puerts\modular.js:125:17)
## context | 编译/运行环境
windows10 x64
unreal engine source code ue5-main
puerts master
puerts使用方式为 继承引擎类模式

## how to reproduce | 复现步骤
1.正常使用puerts。
2.npm安装 reflect-metadata，npm install reflect-metadata --save，tsconfig.json文件添加："emitDecoratorMetadata":true。
3.ue play，失败。
4.删除ts_file_version_info.json和对应项目生成的js文件。
5.执行tsc:build -tsconfig.json。
6.ue play，依然失败。
7.执行puerts.gen，ue play，失败。

## more | 其他

**Comment by chexiongsheng** [comment]
我这里没报错，需要调用些反射的api么？

**Comment by chexiongsheng** [comment]
你ts用的版本是啥？是ts版本低的原因？

**Comment by chexiongsheng** [comment]
npm install reflect-metadata --save
要在哪个目录下执行？

**Comment by YoungForLong** [comment]
> npm install reflect-metadata --save 要在哪个目录下执行？

我是在ts_file_versions_info.json同级目录执行的，ts版本是esnext，声明了decorator，并使用了Reflect.metadata(...)，并未进行调用。

**Comment by YoungForLong** [comment]
> 我这里没报错，需要调用些反射的api么？

编译不会报错，需要实际运行游戏才报错

**Comment by chexiongsheng** [comment]
我运行没报错。
decorator需要是@Reflect.metadata吧？

**Comment by YoungForLong** [comment]
> 我运行没报错。 decorator需要是@Reflect.metadata吧？

需要实现一个自定义的decorator，如下
`import 'reflect-metadata';
export namespace DedicatedServer
{
    export enum ENetExecFlag
    {
        OnServer = 0x1,
        OnClient = 0x2,
    }

    const NetExecFlag = Symbol('NetExecFlag');

    export function NetExec(ExecFlag: ENetExecFlag): any
    {
        return Reflect.metadata(NetExecFlag, ExecFlag);
    }
}`
然后就会报错了

**Comment by chexiongsheng** [comment]
需要声明了TArray的东西，而且上面有decorator。

把TArray改为interface就没问题了，你先试试。

**Comment by YoungForLong** [comment]
> 需要声明了TArray的东西，而且上面有decorator。
> 
> 把TArray改为interface就没问题了，你先试试。

我这边试了下，无需声明任何decorator或者Reflect的使用，只要把tsconfig.json里面的emitDecoratorMetadata修改为true，就会有问题，而且我也没有发现哪里的TArray有使用decorator。
另外，TArray修改为interface是什么意思呢？

**Comment by chexiongsheng** [comment]
更新下吧
