### ISSUE TITLE
[unreal]  Error: can not find [typescript]

### ISSUE THREAD

**Issue by blackredscarf** [Tencent/puerts#914]
## error log | 日志或报错信息
因为排除另一个错误，我把Content/JavaScript目录下的文件都删掉了，然后重新Generate Project files，发现我自己写的ts并没有生产对应的js，然后打开编辑器会报这个错，
```
Puerts: Error: (0x000002E303E679D0) D:\code\unreal\Mars\Mars\Content\JavaScript\puerts\modular.js:96: Error: can not find [typescript]
Error: can not find [typescript]
    at require (D:\code\unreal\Mars\Mars\Content\JavaScript\puerts\modular.js:96:30)
    at D:\code\unreal\Mars\Mars\Content\JavaScript\PuertsEditor\CodeAnalyze.js:5:12
    at D:\code\unreal\Mars\Mars\Content\JavaScript\PuertsEditor\CodeAnalyze.js:3123:3
    at D:\code\unreal\Mars\Mars\Content\JavaScript\PuertsEditor\CodeAnalyze.js:3123:110
```

**Comment by blackredscarf** [comment]
解决办法：删掉tsconfig.json，重新执行`node enable_puerts_module.js`就可以了
