### ISSUE TITLE
[Unity] 导出 UnityEngine.Physics 后, 调用 UnityEngine.Physics.Raycast 方法报错

### ISSUE THREAD

**Issue by Geequlim** [Tencent/puerts#92]
导出 `UnityEngine.Physics` 后, 调用 `UnityEngine.Physics.Raycast` 方法报错，使用反射则正常。

调用代码
```ts
const ray = this.mission.level.view.native.mainCamera.ScreenPointToRay(globalThis['missionUI'].playerInteractivator.cursorPosition);
const hit = $ref<UnityEngine.RaycastHit>();
if (UnityEngine.Physics.Raycast(ray, hit, 500, Mission.ZombieLayerMask | Mission.EnvLayerMask | Mission.ShootableMask)) {
	this.hit = $unref(hit) as UnityEngine.RaycastHit;
	return this.hit.collider.gameObject.layer != Mission.EnvLayer;
}
```

报错日志

```
c# exception:Object reference not set to an instance of an object,stack:  at Puerts.StaticTranslate`1[T].DefaultGetResult (System.Int32 jsEnvIdx, System.IntPtr isolate, Puerts.IGetValueFromJs getValueApi, System.IntPtr value, System.Boolean isByRef) [0x00001] in D:\work\repositories\zombie\project\Assets\Libraries\Puerts\Src\StaticTranslate.cs:29 
  at (wrapper delegate-invoke) Puerts.StaticTranslate`1+GetFunc[UnityEngine.RaycastHit].invoke_T_int_intptr_IGetValueFromJs_intptr_bool(int,intptr,Puerts.IGetValueFromJs,intptr,bool)
  at Puerts.ArgumentHelper.Get[T] (System.Boolean isByRef) [0x0001c] in D:\work\repositories\zombie\project\Assets\Libraries\Puerts\Src\ArgumentHelper.cs:215 
  at PuertsStaticWrap.UnityEngine_Physics_Wrap.F_Raycast (System.IntPtr isolate, System.IntPtr info, System.IntPtr self, System.Int32 paramLen, System.Int64 data) [0x004e3] in D:\work\repositories\zombie\project\Assets\Scripts\Generated\UnityEngine_Physics_Wrap.cs:356 h 
 Error: c# exception:Object reference not set to an instance of an object,stack:  at Puerts.StaticTranslate`1[T].DefaultGetResult (System.Int32 jsEnvIdx, System.IntPtr isolate, Puerts.IGetValueFromJs getValueApi, System.IntPtr value, System.Boolean isByRef) [0x00001] in D:\work\repositories\zombie\project\Assets\Libraries\Puerts\Src\StaticTranslate.cs:29 
  at (wrapper delegate-invoke) Puerts.StaticTranslate`1+GetFunc[UnityEngine.RaycastHit].invoke_T_int_intptr_IGetValueFromJs_intptr_bool(int,intptr,Puerts.IGetValueFromJs,intptr,bool)
  at Puerts.ArgumentHelper.Get[T] (System.Boolean isByRef) [0x0001c] in D:\work\repositories\zombie\project\Assets\Libraries\Puerts\Src\ArgumentHelper.cs:215 
  at PuertsStaticWrap.UnityEngine_Physics_Wrap.F_Raycast (System.IntPtr isolate, System.IntPtr info, System.IntPtr self, System.Int32 paramLen, System.Int64 data) [0x004e3] in D:\work\repositories\zombie\project\Assets\Scripts\Generated\UnityEngine_Physics_Wrap.cs:356 h
	at Shotgun.aim (d:/work/repositories/zombie/project/scripts/src/game/modules/mission/player/skills/aimableskill.ts:58:26)
	at PlayerUnitEventer.PlayerUnitView.onSelectSkill (d:/work/repositories/zombie/project/scripts/src/game/view/mission/player/playerunitview.ts:197:9)
	at PlayerUnitEventer.dispatchEvent (d:/work/repositories/zombie/project/scripts/src/addons/webapi/event.ts:247:13)
	at PlayerUnitEventer.eventShared (d:/work/repositories/zombie/project/scripts/src/addons/tiny/core/eventdispatcher.ts:33:7)
	at PlayerUnitEventer.eventShared (d:/work/repositories/zombie/project/scripts/src/game/modules/mission/player/playerunit.ts:24:77)
	at PlayerUnit.set currentSkill [as currentSkill] (d:/work/repositories/zombie/project/scripts/src/game/modules/mission/player/playerunit.ts:43:16)
	at Level.start (d:/work/repositories/zombie/project/scripts/src/game/modules/mission/level.ts:195:26)
	at Mission.startLevel (d:/work/repositories/zombie/project/scripts/src/game/modules/mission/mission.ts:124:14)
	at  (d:/work/repositories/zombie/project/scripts/src/game/view/ui/windows/deploydialog.ts:115:11)
```

**Comment by Geequlim** [comment]
`RaycastHit` 加入  Blittables 后报错如下
```
c# exception:Object reference not set to an instance of an object,stack:  at System.Buffer.memcpy4 (System.Byte* dest, System.Byte* src, System.Int32 size) [0x00002] in <fb001e01371b4adca20013e0ac763896>:0 
  at System.Buffer.Memcpy (System.Byte* dest, System.Byte* src, System.Int32 size) [0x00073] in <fb001e01371b4adca20013e0ac763896>:0 
  at System.String.memcpy (System.Byte* dest, System.Byte* src, System.Int32 size) [0x00000] in <fb001e01371b4adca20013e0ac763896>:0 
  at PuertsStaticWrap.UnityEngine_RaycastHit_Wrap.StaticGetter (System.Int32 jsEnvIdx, System.IntPtr isolate, Puerts.IGetValueFromJs getValueApi, System.IntPtr value, System.Boolean isByRef) [0x00011] in D:\work\repositories\zombie\project\Assets\Scripts\Generated\UnityEngine_RaycastHit_Wrap.cs:302 
  at (wrapper delegate-invoke) Puerts.StaticTranslate`1+GetFunc[UnityEngine.RaycastHit].invoke_T_int_intptr_IGetValueFromJs_intptr_bool(int,intptr,Puerts.IGetValueFromJs,intptr,bool)
  at Puerts.ArgumentHelper.Get[T] (System.Boolean isByRef) [0x0001c] in D:\work\repositories\zombie\project\Assets\Libraries\Puerts\Src\ArgumentHelper.cs:215 
  at PuertsStaticWrap.UnityEngine_Physics_Wrap.F_Raycast (System.IntPtr isolate, System.IntPtr info, System.IntPtr self, System.Int32 paramLen, System.Int64 data) [0x004e3] in D:\work\repositories\zombie\project\Assets\Scripts\Generated\UnityEngine_Physics_Wrap.cs:356  
 Error: c# exception:Object reference not set to an instance of an object,stack:  at System.Buffer.memcpy4 (System.Byte* dest, System.Byte* src, System.Int32 size) [0x00002] in <fb001e01371b4adca20013e0ac763896>:0 
  at System.Buffer.Memcpy (System.Byte* dest, System.Byte* src, System.Int32 size) [0x00073] in <fb001e01371b4adca20013e0ac763896>:0 
  at System.String.memcpy (System.Byte* dest, System.Byte* src, System.Int32 size) [0x00000] in <fb001e01371b4adca20013e0ac763896>:0 
  at PuertsStaticWrap.UnityEngine_RaycastHit_Wrap.StaticGetter (System.Int32 jsEnvIdx, System.IntPtr isolate, Puerts.IGetValueFromJs getValueApi, System.IntPtr value, System.Boolean isByRef) [0x00011] in D:\work\repositories\zombie\project\Assets\Scripts\Generated\UnityEngine_RaycastHit_Wrap.cs:302 
  at (wrapper delegate-invoke) Puerts.StaticTranslate`1+GetFunc[UnityEngine.RaycastHit].invoke_T_int_intptr_IGetValueFromJs_intptr_bool(int,intptr,Puerts.IGetValueFromJs,intptr,bool)
  at Puerts.ArgumentHelper.Get[T] (System.Boolean isByRef) [0x0001c] in D:\work\repositories\zombie\project\Assets\Libraries\Puerts\Src\ArgumentHelper.cs:215 
  at PuertsStaticWrap.UnityEngine_Physics_Wrap.F_Raycast (System.IntPtr isolate, System.IntPtr info, System.IntPtr self, System.Int32 paramLen, System.Int64 data) [0x004e3] in D:\work\repositories\zombie\project\Assets\Scripts\Generated\UnityEngine_Physics_Wrap.cs:356 
	at Gun.aim (d:/work/repositories/zombie/project/scripts/src/game/modules/mission/player/skills/aimableskill.ts:60:24)
	at PlayerUnitEventer.PlayerUnitView.onSelectSkill (d:/work/repositories/zombie/project/scripts/src/game/view/mission/player/playerunitview.ts:197:9)
	at PlayerUnitEventer.dispatchEvent (d:/work/repositories/zombie/project/scripts/src/addons/webapi/event.ts:247:13)
	at PlayerUnitEventer.eventShared (d:/work/repositories/zombie/project/scripts/src/addons/tiny/core/eventdispatcher.ts:33:7)
	at PlayerUnitEventer.eventShared (d:/work/repositories/zombie/project/scripts/src/game/modules/mission/player/playerunit.ts:24:77)
	at PlayerUnit.set currentSkill [as currentSkill] (d:/work/repositories/zombie/project/scripts/src/game/modules/mission/player/playerunit.ts:43:16)
	at Level.start (d:/work/repositories/zombie/project/scripts/src/game/modules/mission/level.ts:195:26)
	at Mission.startLevel (d:/work/repositories/zombie/project/scripts/src/game/modules/mission/mission.ts:129:14)
	at  (d:/work/repositories/zombie/project/scripts/src/game/view/ui/windows/deploydialog.ts:115:11)
```
