### ISSUE TITLE
[Unity] 2021.3.8 插件1.4.0 报错task.GetAwaiter(...).OnCompleted is not a function in puerts\csharp.mjs

### ISSUE THREAD

**Issue by wardehuang** [Tencent/puerts#966]
## error log | 日志或报错信息
```
unhandledRejection,TypeError: task.GetAwaiter(...).OnCompleted is not a function,TypeError: task.GetAwaiter(...).OnCompleted is not a function
    at puerts\csharp.mjs:126:27
    at new Promise (<anonymous>)
    at taskToPromise (puerts\csharp.mjs:125:12)
    at Network.get (<anonymous>:206:73)
    at Main.checkUpdate (<anonymous>:539:36)
    at Main.start (<anonymous>:514:33)
    at Object../src/Main.ts (<anonymous>:548:12)
    at __webpack_require__ (<anonymous>:593:40)
    at <anonymous>:648:36
```
## context | 编译/运行环境
Windows 64 Mono - 运行正常
Windows 64 IL2CPP - **运行报错**
微信小游戏 - **运行报错**

## how to reproduce | 复现步骤
1. Ts代码中使用await $promise(task)

**Comment by zombieyang** [comment]
参考
https://github.com/Tencent/puerts/issues/778
https://github.com/Tencent/puerts/issues/793

**Comment by wardehuang** [comment]
好的，感谢。没留意到closed的issue

**Comment by wardehuang** [comment]
我这边尝试了另外一种解决方案，仅在Editor, Windows 64 Mono, Windows 64 IL2CPP，微信小游戏上测试过。大佬能帮忙评估下正确性和可行性吗？

**修改csharp.mjs 中的 taskToPromise**


```
function taskToPromise(task) {
    return new Promise((resolve, reject) => {
        let unsafe = !task.GetAwaiter().OnCompleted || typeof (task.GetAwaiter().OnCompleted) != "function";

        let handle = () => {
            let t = task;
            task = undefined;
            if (t.IsFaulted) {
                if (t.Exception) {
                    if (t.Exception.InnerException) {
                        reject(t.Exception.InnerException.Message);
                    } else {
                        reject(t.Exception.Message);
                    }
                } else {
                    reject("unknow exception!");
                }
            } else {
                resolve(unsafe ? t.GetAwaiter().GetResult() : t.Result);
            }
        }

        if (unsafe)
            task.GetAwaiter().UnsafeOnCompleted(handle);
        else
            task.GetAwaiter().OnCompleted(handle);
    });
}
```


主要修改：
**OnCompleted => UnsafeOnCompleted
t.Result => t.GetAwaiter().GetResult()**

> 参考 #778 #793

**Comment by zombieyang** [comment]
我理解这个问题是裁剪造成的，换个接口真的可以么...

能否在demo项目上试试？可以顺便PR加一个关于异步的example

**Comment by wardehuang** [comment]
在Demo项目中试了一下，打包出来测试，得到一样的结果，代码如下：
```

using UnityEngine;
using Puerts;
using System.Threading.Tasks;
using System;

namespace PuertsTest
{
    public class Promise : MonoBehaviour
    {
        JsEnv jsEnv;

        public static async Task MakeATask()
        {
            long now = DateTimeOffset.Now.ToUnixTimeMilliseconds();
            var task = new Task<int>(() =>
            {
                while (true)
                {
                    if (DateTimeOffset.Now.ToUnixTimeMilliseconds() - now > 3000)
                    {
                        break;
                    }
                }
                return 30;
            });

            task.Start();

            await task;
        }

        void Start()
        {
            Debug.LogError("Development Build!!!");

            jsEnv = new JsEnv();

            // 以下Windows 64 IL2CPP会报错
            jsEnv.Eval(@"
                const CS = require('csharp');
                
                (async function asd() {
                    console.log(11);
                    await taskToPromise(CS.PuertsTest.Promise.MakeATask());
                    console.log(22);
                })();

                function taskToPromise(task) {
                    return new Promise((resolve, reject) => {
                        task.GetAwaiter().OnCompleted(() => {
                            let t = task;
                            task = undefined;
                            if (t.IsFaulted) {
                                if (t.Exception) {
                                    if (t.Exception.InnerException) {
                                        reject(t.Exception.InnerException.Message);
                                    } else {
                                        reject(t.Exception.Message);
                                    }
                                } else {
                                    reject('unknow exception!');
                                }
                            } else {
                                resolve(t.Result);
                            }
                        });
                    });
                }
            ");

            // 以下Windows 64 IL2CPP正常运行
            jsEnv.Eval(@"
                (async function asd2() {
                    console.log(33);
                    await taskToPromise2(CS.PuertsTest.Promise.MakeATask());
                    console.log(44);
                })();

                function taskToPromise2(task) {
                    return new Promise((resolve, reject) => {
                        task.GetAwaiter().UnsafeOnCompleted(() => {
                            let t = task;
                            task = undefined;
                            if (t.IsFaulted) {
                                if (t.Exception) {
                                    if (t.Exception.InnerException) {
                                        reject(t.Exception.InnerException.Message);
                                    } else {
                                        reject(t.Exception.Message);
                                    }
                                } else {
                                    reject('unknow exception!');
                                }
                            } else {
                                resolve(t.GetAwaiter().GetResult());
                            }
                        });
                    });
                }
            ");
        }

        void OnDestroy()
        {
            jsEnv.Dispose();
        }
    }
}

```

Demo的生成列表只需要添加刚加的新类：
```typeof(PuertsTest.Promise)```

**Comment by zombieyang** [comment]
试了下确实可以，关键在于`UnsafeOnCompleted`，有可能是Unity自身有使用UnsafeOnCompleted所以它不会被默认裁剪？

查了下此处用`UnsafeOnCompleted`而非`OnCompleted`确实也没大问题。

感谢贡献。你可以提个PR修改https://github.com/Tencent/puerts/blob/master/unity/Assets/Puerts/Runtime/Resources/puerts/csharp.mjs#L122 。这样Contributors里能留下你名字。

**Comment by wardehuang** [comment]
没看源码，从现象看起来应该是的，默认不裁剪。PR就不提了，你修改就好:D
